### ISSUE TITLE
Data is duplicated on reloading seeds that are using an external table

### ISSUE THREAD

**Issue by dejan** [databricks/dbt-databricks#114]
### Describe the bug

When seeds are configured as an external table, the data is getting duplicated on reload. 

### Steps To Reproduce

I create a repo with a demo of the issue: https://github.com/dejan/dbt-demo-inconsistent-seeds but here is a short instruction on how to reproduce:

Have seeds/cities.yml:
```csv
id,name
1,berlin
2,paris
```

Have seeds/countries.yml:
```csv
id,name
1,germany
2,france
```

Configure one seed to use managed table (by default) and another one to use external (by setting location_root).

```yml
seeds:
  foo:
    cities:
    countries:
      location_root: "{{ env_var('LOCATION') }}"
```

Run dbt seed *twice*:

    dbt seed && dbt seed

Observe the content in both tables.

```sql
select * from foo.cities
```

|id|name|
|--|----|
|1|berlin|
|2|paris|

```sql
select * from foo.countries
```

|id|name|
|--|----|
|1|germany|
|1|germany|
|2|france|
|2|france|

### Expected behavior
The behavior should be consistent regardless of the table type. The data should be reloaded - ie there should be no duplicates.

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.1.0
  - latest:    1.1.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - spark:      1.1.0 - Up to date!
  - databricks: 1.1.0 - Up to date!
```

**The operating system you're using: OS X Big Sur**

**The output of `python --version`: Python 3.8.10**

**Comment by jtcohen6** [comment]
@dejan Ah, I think this is an issue we were aware of over in `dbt-spark`: https://github.com/dbt-labs/dbt-spark/issues/112

There was a PR opened for it some months ago, but we didn't manage to get it over the finish line: https://github.com/dbt-labs/dbt-spark/pull/182

**Comment by allisonwang-db** [comment]
Hi @dejan, when you drop an external table, only the associated metadata are removed. Spark will not delete the underlying data files. That's why you see duplicated rows when running `dbt seed` twice with an external table. I am wondering what's your use case for using an external table instead of a managed table?

**Comment by dejan** [comment]
@allisonwang-db I understand the difference between the two. My point is - that difference should not affect the behavior of dbt - materialization should be consistent like it is for models for example.  

> I am wondering what's your use case for using an external table instead of a managed table?

What's wrong with using external tables?

**Comment by allisonwang-db** [comment]
@dejan My point is to see if you have any specific use case for external tables so that we could provide workarounds for your workloads. I am not against making the behavior for external tables consistent with managed tables in dbt as the issue has been raised by many users in dbt-spark.

**Comment by dejan** [comment]
@allisonwang-db we already have the workaround - we're deleting the content with the pre-hook but obviously that's not ideal as it it's not atomic and it pollutes the version history. 

External tables better fit our company's data management strategy.
