### ISSUE TITLE
Support ZORDER on models as model configuration

### ISSUE THREAD

**Issue by bilalaslamseattle** [databricks/dbt-databricks#122]
### Describe the feature
`ZORDER` is a useful way to get natural colocation for data. It can only be run as part of the [OPTIMIZE](https://docs.databricks.com/spark/latest/spark-sql/language-manual/delta-optimize.html) command. I would like to be able to set it as model configuration. In the implementation, we would run the OPTIMIZE command, which would use the model metadata to figure out the right ZORDER columns

### Who will this benefit?
Analytics engineers who want to keep model metadata in one location - the model itself.

**Comment by tfayyaz** [comment]
The spark_utils package has these that could potentially be reused for this:

https://github.com/dbt-labs/spark-utils#useful-macros-maintenance

- spark_optimize_delta_tables: Runs optimize for all matched Delta tables
- spark_vacuum_delta_tables: Runs vacuum for all matched Delta tables
- spark_analyze_tables: Compute statistics for all matched tables

Thanks
Tahir

**Comment by data-blade** [comment]
still interested in this too
