### ISSUE TITLE
Databricks Workflows GA

### ISSUE THREAD

**Issue by nicolai92** [databricks/dbt-databricks#156]
Hi,

I build a data vault model for a customer using dbt and want to use the Databricks workflow integration as mentioned here: https://github.com/databricks/dbt-databricks/blob/main/docs/databricks-workflows.md

Is there a way to apply for the private preview, or can you estimate, when the feature becomes public preview or GA?

Best,
Nicolai

**Comment by KoningJasper** [comment]
Hi @nicolai92. It's going into public preview this week for workspaces which have access to serverless warehouses.

**Comment by bilalaslamseattle** [comment]
+1 on what @KoningJasper said. Closing this issue out
