### ISSUE TITLE
support user incremental predicates on merge 

### ISSUE THREAD

**Issue by dave-connors-3** [databricks/dbt-databricks#160]
### Describe the feature

Users should be able to supply incremental models with arbitrary predicates during the merge step to prevent unnecessary table scan for massive data sets. 

### Describe alternatives you've considered
None

### Additional context
See: 
- [Core Issue 5680](https://github.com/dbt-labs/dbt-core/issues/5680)
- [Core Issue 3293](https://github.com/dbt-labs/dbt-core/issues/3293)
- [Core PR 5702](https://github.com/dbt-labs/dbt-core/pull/5702)

### Who will this benefit?
users with extremely large datasets who want to limit the scan of their merge operations on incremental models!

### Are you interested in contributing this feature?
Yes

**Comment by bilalaslamseattle** [comment]
@ueshin @superdupershant seems like a reasonable ask since it's supported in other DWs.
