### ISSUE TITLE
Can't get Python models running on `1.3.0b0`

### ISSUE THREAD

**Issue by b-per** [databricks/dbt-databricks#175]
### Describe the bug
I am trying to run Python models using the `dbt-dtabricks` adapter but get some errors.

### Steps To Reproduce
- Create some models in your dbt project.
- With only SQL models, they run correctly.
- When adding a Python model, the run fails with the error: 
```
Unhandled error while executing model.my_project.my_model
Python model doesn't support SQL Warehouses
```

My `profiles.yml` is configured with the `http_path` config.
- If I add a `cluster` in addition to `http_path`, I still get the error.
- If I keep the `cluster` and remove `http_path` I get the error:
```
dbt.exceptions.DbtProfileError: Runtime Error
`http_path` must set when using the dbsql method to connect to Databricks
```

### Expected behavior
The Python model runs correctly

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.3.0-b2
  - latest:    1.2.1    - Ahead of latest version!

Plugins:
  - databricks: 1.3.0b0 - Ahead of latest version!
  - snowflake:  1.3.0b2 - Ahead of latest version!
  - spark:      1.3.0b2 - Ahead of latest version!
```

### Additional context
Is there specific config that needs to filled-in in `profiles.yml` to work with Python models?

**Comment by ueshin** [comment]
Right, so far Python model only works on the multi-purpose clusters.
The discussion to provide a way to have a separate config to run on the multi-purpose clusters even when the main connection is to SQL Warehouse. dbt-labs/dbt-spark#444.

**Comment by jtcohen6** [comment]
@ueshin  Just to clarify — for folks who want to use Python models with `dbt-databricks` _today_ — they need to specify an additional `cluster_id` field in their `profiles.yml`. Does that sound right?

I left a new comment in https://github.com/dbt-labs/dbt-spark/issues/444#issuecomment-1253344541. I _think_ you could use the pseudo-code there to allow users to specify `cluster_id` / `cluster` as a model-level configuration, and pull that into the `submit_python_job`, in case they have not added it as configuration in `profiles.yml`, or specified it within their `http_path` [to be extracted](https://github.com/databricks/dbt-databricks/blob/fe61d6fa539c8a8eb3d43ca6565fd4a16cbcb411/dbt/adapters/databricks/connections.py#L152-L158).

Also a thought about reconciling the teensy naming difference between `cluster` + `cluster_id`.

**Comment by ueshin** [comment]
The `cluster_id` is extracted from the provided `http_path` if it's for an all-purpose cluster, so the users don't need to specify the additional config.
The `cluster_id` will not be exposed to users.

I'm hoping users could specify the `http_path` in the model config instead of `cluster` or `cluster_id` to be consistent with the config names of `profile`, and use it to call APIs:

```py
def model(...):
    dbt.config(http_path='...')
    ....
```
