### ISSUE TITLE
Remove submit_python_job from Jinja context

### ISSUE THREAD

**Issue by ChenyuLInx** [databricks/dbt-databricks#182]
### Describe the feature
With the latest change in dbt-core, we should consider remove [this line](https://github.com/databricks/dbt-databricks/blob/main/dbt/adapters/databricks/impl.py#L263) so that user won't have access to `adapter.submit_python_job` in Jinja macros directly. This function is used by [a context member directly in `dbt-core`](https://github.com/dbt-labs/dbt-core/pull/5822/files#diff-d14b7d00e52da5da96bfb3bdef414e9289d923efe0a9cdadd716d792c7199535R1263).

Also something related to this area, we recently refactored the function here a little bit(dbt-core, dbt-spark). Maybe we want to follow the style there so any updates are automatically included

### Additional context
This would help dbt keep being opinionated about when certain operation should happen

**Comment by ChenyuLInx** [comment]
@ueshin  I just saw your PR after opending this issue. https://github.com/databricks/dbt-databricks/pull/178. It would close it completely

**Comment by ueshin** [comment]
@ChenyuLInx Just to confirm, you mean the current change at #178 already satisfies your requirement, right?

**Comment by ChenyuLInx** [comment]
Yes, also updated my previous comment.
