### ISSUE TITLE
"Failed to Connect" Error Could be more illustrative 

### ISSUE THREAD

**Issue by faithlierheimer** [databricks/dbt-databricks#218]
### Describe the bug
When trying to connect to dbt from the command line, I received a fail to connect error that was actually about SSL certificates and not about the connection issue at all. 

### Steps To Reproduce
Have an invalid key or connection issue. the dbt-databricks adapter will show the error "Failed to Connect", but it will not display the root issue. I had to use advanced debugging functionality to figure out whether the issue lay with dbt or with the computer itself. 

### Expected behavior
I want the error to show whether the "Failed to Connect" issue is from dbt itself (in this case it wasn't), or if it's an issue with the computer.

### Screenshots and log output
[If applicable, add screenshots or log output to help explain your problem.
](https://github.com/databricks/dbt-databricks/blob/3faf4a4af67675f10dec3e986aa788fa5b89506f/dbt/adapters/databricks/connections.py#L544-L592)
### System information
**The output of `dbt --version`:**
```
1.3
```

**The operating system you're using:**
MacOS monterey
**The output of `python --version`:**
3.9
### Additional context

This is the error the connection issue actually came from. 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/databricks/sql/__init__.py", line 28, in connect
    return Connection(server_hostname, http_path, access_token, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/databricks/sql/client.py", line 269, in __init__
    response = self._make_request(self._client.OpenSession, open_session_req)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/databricks/sql/client.py", line 420, in _make_request
    self._handle_request_error(error_info, attempt, elapsed)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/databricks/sql/client.py", line 341, in _handle_request_error
    raise OperationalError(user_friendly_error_message, error_info.error)
databricks.sql.exc.OperationalError: ('Error during request to server', SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))

**Comment by ueshin** [comment]
Hi @faithlierheimer, thanks for trying dbt-databricks!

For the error message, have you checked `dbt.log` file? It must contain more detailed error messages.

Thanks.

**Comment by faithlierheimer** [comment]
@ueshin Yes, I did check dbt log but it still only showed the "Failed to connect" error--it was only when I pasted the base python code from the actual databricks connector that it actually revealed the error surrounding my SSL certificate. 

Here is the python code I ran that revealed the actual SSL error, with my details redacted, ha! 

`>>> conn = dbsql.connect(server_hostname="", http_path="", access_token = "")`

**Comment by ueshin** [comment]
The error messages in the **Additional context** of the issue description is actually from pretty old `databricks-sql-connector` that I guess is `1.0.x`. Is that the same one as `dbt-databricks` uses? Could you try with the recent one, like `2.0.5` or `2.1.0`?
Also the detailed errors are in the `debug` level logs. Could you make sure the debug level logs are available?
Thanks.

**Comment by faithlierheimer** [comment]
hi @ueshin , still working on getting my SSL certificate issue issue resolved--but this is what i have for logs. will come back once i can try again with my SSL thing resolved if that's ok!
<img width="1384" alt="debug" src="https://user-images.githubusercontent.com/54042545/197361530-0d805fdf-8dbf-4423-a2d8-7380f579b3d7.png">

**Comment by Charan-hf** [comment]
Hi,

I am facing same issue, can anyone help me with the fix?
