### ISSUE TITLE
dbt run error: Catalog namespace is not supported.

### ISSUE THREAD

**Issue by jakub-auger** [databricks/dbt-databricks#238]
### Describe the bug
New dbt project pointing at a databricks cluster without unity catalog
looks like dbt is trying to use it despite deleting the catalog tag from the profile (or setting it to null)

### Steps To Reproduce
dbt run

### Expected behavior
models built

### Screenshots and log output
[0m18:33:42.551967 [debug] [Thread-1 (]: Databricks adapter: <class 'databricks.sql.exc.ServerOperationError'>: Catalog namespace is not supported.
[0m18:33:42.551967 [debug] [Thread-1 (]: Databricks adapter: diagnostic-info: org.apache.hive.service.cli.HiveSQLException: Error running query: org.apache.spark.sql.AnalysisException: Catalog namespace is not supported.

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.3.1
  - latest:    1.3.1 - Up to date!

Plugins:
  - databricks: 1.3.2 - Up to date!
  - spark:      1.3.0 - Up to date!
```

**The operating system you're using:**
windows 10
**The output of `python --version`:**
Python 3.10.8
### Additional context
databricks version 10.4 LTS

**Comment by ueshin** [comment]
Yes, please don't specify `catalog` in the profile if you don't use Unity Catalog.

**Comment by jakub-auger** [comment]
makes no difference
```
stanford_genomics:
  outputs:
    prod:
      host: adb-xxxx.2.azuredatabricks.net
      schema: default
      http_path: sql/protocolv1/o/5xxxxxxxx
      threads: 4
      token: xxxxxx
      type: databricks
  target: prod
```

result is still

````
18:58:07  Concurrency: 4 threads (target='prod')
18:58:07
18:58:07  1 of 1 START sql view model clinvar.variant_summary_history_dbt ................ [RUN]
18:58:10  1 of 1 ERROR creating sql view model clinvar.variant_summary_history_dbt ....... [ERROR in 2.66s]
18:58:11
18:58:11  Finished running 1 view model in 0 hours 0 minutes and 9.32 seconds (9.32s).
18:58:11
18:58:11  Completed with 1 error and 0 warnings:
18:58:11
18:58:11  Runtime Error in model variant_summary_history_dbt (models\clinvar\variant_summary_history_dbt.sql)
18:58:11    Catalog namespace is not supported.
18:58:11
18:58:11  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```

**Comment by ueshin** [comment]
Could yo double-check the dbt project is pointing the profile above?
I guess it's pointing another profile that includes `schema: clinvar`.

Could you try `dbt debug` command?

**Comment by jakub-auger** [comment]
dbt debug is fine
```
Using profiles.yml file at C:\Users\jakub\.dbt\profiles.yml
Using dbt_project.yml file at C:\Users\jakub\repos\dbt\stanford_genomics\dbt_project.yml

Configuration:
  profiles.yml file [OK found and valid]
  dbt_project.yml file [OK found and valid]

Required dependencies:
 - git [ERROR]

Connection:
  host: adb-xxxxxxxx.2.azuredatabricks.net
  http_path: sql/protocolv1/o/xxxxxxx
  schema: default
  Connection test: [OK connection ok]
```
this is a new project so there is only one target in the profile.yml

i'm overriding the schema in the config() for the model. i tried it into the default schema and it didn't work either
```
{{ config(
    materialized='view',
    schema='clinvar',
)
}}
```

**Comment by ueshin** [comment]
That's interesting.

Is it possible to share the reproducible model? It doesn't need to include your actual model, but simple enough to reproduce the issue.

**Comment by jakub-auger** [comment]
oops... user error
my source.yml was bad.. i had a database: node in there... so the source yml was generating a 3 part object.

Thanks for looking into it and sorry for wasting your time!

**Comment by ueshin** [comment]
Got it! No worries, I'm happy to hear the issue was fixed anyway. :)
