### ISSUE TITLE
Views fail to build if a table has been materialized in the target warehouse.

### ISSUE THREAD

**Issue by randypitcherii** [databricks/dbt-databricks#244]
### Describe the bug
When building a model materialized as a view, if the model has been previously built as a table dbt will fail on build because the view materialization does not properly drop the existing table.

### Steps To Reproduce
- create a model `select 1 as col`
- configure this model as a table
- execute `dbt build` on this model
- change this model materialization to `view`
- execute `dbt build` on this model again
- observe the build fails 

### Expected behavior
View materializations should happily drop any existing materializations in the target warehouse as part of the build process.

**Comment by fraserharris** [comment]
@randypitcherii do you get an error like this?
```
01:01:24 Runtime Error
01:01:24 Cannot drop a view with DROP TABLE. Please use DROP VIEW instead
```
