### ISSUE TITLE
Parse error for '\' for dbt seed on dbt-databricks adapter

### ISSUE THREAD

**Issue by gunnava** [databricks/dbt-databricks#249]
**### Describe the bug**
With the dbt databricks adaptor dbt seed is throwing a parse error for /; . dbt seed command runs fine when using the dbt-spark adapter.
Rows in the CSV that cause issues:
Macy's Canada,Macy's 
Macy\'s,Macy's

**### Steps To Reproduce**
Create a seed csv file with the data that contain spl character`  \`

Sample data: 
store1,store2
Macy's Canada,Macy's
Macy's,Macy's
Run dbt seed on data bricks warehouse using dbt-databricks adapter. it throws the below error:
`[PARSE_SYNTAX_ERROR] Syntax error at or near ','`

### Expected behavior
dbt seed command should parse the special characters as well

### Screenshots and log output
debug logs for both the runs using dbt-sparks adapter and dbt-databricks adapter are attached.
[console_output_dbt-sparks.txt](https://github.com/databricks/dbt-databricks/files/10386877/console_output_dbt-sparks.txt)
[dbt seed_output_dbt-databricks.txt](https://github.com/databricks/dbt-databricks/files/10386878/dbt.seed_output_dbt-databricks.txt)

### System information
**The output of `dbt --version`:**
```
"dbt_version": "1.3.2", "dbt_databricks_version": "1.3.2",
```
Works perfectly in dbt-spark adaptor but not in dbt-databricks adaptor

**Comment by ueshin** [comment]
Which version of `databricks-sql-connector` are you using?
Could you try to upgrade it to at least `2.2.0`?
I think it's fixed at https://github.com/databricks/databricks-sql-python/commit/d2d9015046852944bc5267279a14055fd6bf23e8 that is included in `2.2.0`.

**Comment by gunnava** [comment]
Thank you. The issue is fixed in databricks-sql-connector >= 2.2.0
