### ISSUE TITLE
Adapter-specific `target` information

### ISSUE THREAD

**Issue by oynek** [databricks/dbt-databricks#253]
### Describe the feature
For Snowflake as well as BigQuery `target` specific information is available in the Jinja context.

See for example: https://docs.getdbt.com/reference/dbt-jinja-functions/target

Similar information would also be desirable for the dbt-databricks adapter, especially the `catalog`.

### Describe alternatives you've considered
The alternative would be to build a workaround using the available environment variables like `target.name`.

### Additional context

```
{% macro generate_schema_name(custom_schema_name, node) -%}

    {%- set default_schema = target.schema -%}
    {%- if custom_schema_name is none -%}

        {{ default_schema }}

    {%- elif target.catalog == 'prep' -%}
            
        {{ custom_schema_name | trim }}

    {%- else -%}

        {{ default_schema }}_{{ custom_schema_name | trim }}

    {%- endif -%}

{%- endmacro %}
```

### Who will this benefit?
See Additional context. This would allow more granular control of behavior within the Unity Catalog for individual models.

**Comment by ueshin** [comment]
I think `target.catalog` is available if it's set in the `profile.yml`.

I defined the macro like:

```
{% macro databricks__generate_schema_name(custom_schema_name, node) -%}
    {%- set default_database = target.catalog -%}
    {%- set default_schema = target.schema -%}
    {%- if custom_schema_name is none -%}

        {{ default_database }}_{{ default_schema }}

    {%- else -%}

        {{ default_database }}_{{ default_schema }}_{{ custom_schema_name | trim }}

    {%- endif -%}

{%- endmacro %}
```

then it generated the schama name prefixed with the `target.catalog` value.
