### ISSUE TITLE
dbt seed strips single quotes from values in csv

### ISSUE THREAD

**Issue by dbeatty10** [databricks/dbt-databricks#254]
### Describe the bug

Most of the following content is copy-pasted from https://github.com/dbt-labs/dbt-core/issues/6020 originally reported by @jakub-auger.

@otosky [noted that](https://github.com/dbt-labs/dbt-core/issues/6020#issuecomment-1380592154):
> this is actually a dependency issue on the [databricks-sql-connector](https://pypi.org/project/databricks-sql-connector/) package
> 
> I noticed that this issue recently went away when someone on my team accidentally bumped that package from 2.1.0 -> 2.2.0
> 
> (we're on dbt-databricks 1.3.2 fwiw)

### Potential Solution
Assuming that `databricks-sql-connector>=2.2.0` indeed fixes this, then this issue could be solved by updating the dbt-databricks adapter [here](https://github.com/databricks/dbt-databricks/blob/4b56862db1947239585315e9361cc479a547f041/setup.py#L59) to reflect that version.

### Current Behavior

csv contents

col_1,col_2
"Joes Diner",123
"Joe's Diner",456

run dbt seed

contents of created seed table are
Joes Diner,123
Joes Diner,456

### Expected Behavior

contents of created seed table are
Joes Diner,123
Joe's Diner,456

### Steps To Reproduce

create /seed/test.csv file with the following contents
col_1,col_2
"Joes Diner",123
"Joe's Diner",456

run dbt seed -s test

on your databricks instance, run select * from default.test

### Environment

```markdown
- OS:
windows 11
- Python:
python --version
Python 3.9.12
- dbt:
dbt --version
Core:
  - installed: 1.2.2
  - latest:    1.2.2 - Up to date!

Plugins:
  - databricks:        1.2.3  - Up to date!
  - postgres:          1.1.0  - Not compatible!
  - spark:             1.2.0  - Up to date!
  - sqlserver:         0.20.1 - Not compatible!
  - synapse:           0.20.0 - Not compatible!
  - synapseserverless: 0.20.0 - Not compatible!
```

**Comment by ueshin** [comment]
The dependent version is already upgraded at #250.
Please upgrade `databricks-sql-connector` to `2.2.0` or above for a workaround.

**Comment by dbeatty10** [comment]
> The dependent version is already upgraded at #250. Please upgrade `databricks-sql-connector` to `2.2.0` or above for a workaround.
> 
> Thanks.

Awesome @ueshin !

Closing as duplicate of https://github.com/databricks/dbt-databricks/issues/249
