### ISSUE TITLE
bigint values in seeds >= 16 digits get mangled in `dbt seed`

### ISSUE THREAD

**Issue by otosky** [databricks/dbt-databricks#261]
### Describe the bug
A seed with field values that should be properly represented as bigints gets populated to the destination table incorrectly.  This seems to happen with values exceeding 16 digits, but still below the Java BigInt max of 9223372036854775807. 

### Steps To Reproduce
1. Create a test seed:
seed_bigint_test.csv
```
f1,f2
a,10000000000000001
b,10000000000000002
c,10000000000000003
d,10000000000000004
e,10000000000000005
```

2. Run `dbt seed`
3. Check output of table:
![Screenshot 2023-01-25 at 10 51 44 AM](https://user-images.githubusercontent.com/42260747/214610424-c8c57787-30df-473c-a78e-ab786e6d1576.png)

---

For what it's worth, this seed populates just fine:

```
f1,f2
a,1000000000000001
b,1000000000000002
c,1000000000000003
d,1000000000000004
e,1000000000000005
```

where the bigint is only 16 digits long

### Expected behavior

I would expect valid bigint values to be populated in the destination table exactly and without changes from the seed csv.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**The output of `dbt --version`:**
```
dbt --version
Core:
  - installed: 1.3.2
  - latest:    1.4.0 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - databricks: 1.3.2 - Up to date!
  - spark:      1.3.0 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```

**The operating system you're using:**

MacOS Ventura 13.2

**The output of `python --version`:**
Python 3.9.5

### Additional context
Databricks runtime 11.3 LTS
databricks-sql-connector  2.3.0

**Comment by ValdarT** [comment]
For anyone else ending up here, you can mitigate by specifying the type explicitly in the config ([docs](https://docs.getdbt.com/reference/resource-configs/column_types))

```
version: 2

seeds:
  - name: seed_bigint_test
    config:
      column_types:
        f2: bigint
```
