### ISSUE TITLE
Including `rows_affected`-like information in the results on-run-end context variable

### ISSUE THREAD

**Issue by jeremyyeo** [databricks/dbt-databricks#268]
### Describe the feature
This is the same as outlined in dbt-spark here:

https://github.com/dbt-labs/dbt-spark/issues/497

But is essentially the same with dbt-databricks.

```
adapter_response={'_message': 'OK'}
```

### Describe alternatives you've considered
Don't think there's a good alternative here.

### Who will this benefit?
Users who need fine grained audit information in their runs - how many rows affected when a model runs, etc. In particular the [`dbt_artifacts`](https://github.com/brooklyn-data/dbt_artifacts) package writes rows_affected into their tables but for databricks/spark it's always 0.

### Are you interested in contributing this feature?
Let us know if you want to write some code, and how we can help.

```
$ dbt --version
Core:
  - installed: 1.3.2
  - latest:    1.4.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - databricks: 1.3.2 - Update available!
```

**Comment by benc-db** [comment]
closing as duplicate of https://github.com/databricks/dbt-databricks/issues/351.  Thanks for reporting, it is being considered.
