### ISSUE TITLE
Support for azure authentication mechanisms.

### ISSUE THREAD

**Issue by superdupershant** [databricks/dbt-databricks#28]
### Describe the feature
Beyond simple PAT tokens supporting some of Azure AAD based authentication would great. 

### Additional context
[dbt-sqlserver](https://github.com/dbt-msft/dbt-sqlserver/blob/master/dbt/adapters/sqlserver/connections.py) is a good example of how to get vaild auth tokens, and databricks-sql-connector already supports taking auth_token arguments.

### Who will this benefit?
Users trying to use AAD based SSO or other features.

**Comment by dataders** [comment]
I'm a big supported of this feature, and I'd love to help out, as I originally "assisted" with adding AAD auth to dbt-sqlserver. 👀: @JCZuurmond

**Comment by superdupershant** [comment]
Awesome to hear that Anders! At least for Databricks it would be pretty straight forward if we had an easy way to pull in all the Auth code from dbt-sqlserver. Whichever AAD auth mode the user selects eventually they get a token back, that token would just be used in place of the password with the Databricks connection and if the workspace is AAD enabled the connection will succeed.

**Comment by bilalaslamseattle** [comment]
@ueshin this issue is almost a year old now. It seems like the most bitter pill to swallow is the Azure CLI (yikes).

**Comment by sdebruyn** [comment]
For those authenticating using Azure, you can use Az CLI to get a valid token and then use that in the regular config:

1. Sign in with Az CLI: `az login`
1. Fetch an access token for Databricks (the ID is static for all Databricks workspaces): `aad_token_response=$(az account get-access-token --resource 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d)`
1. Parse the access token (you need jq installed): `aad_token=$(jq .accessToken -r <<< "$aad_token_response")`
1. Store the token in an environment variable `export DATABRICKS_AAD_TOKEN=$aad_token`

Then in your profiles.yml you can authenticate using the stored token: `token: "{{ env_var('DATABRICKS_AAD_TOKEN') }}"`

**Comment by sdebruyn** [comment]
But as discussed above, it would be nicer to use the az-identity package to retrieve a token automatically so that you can also use this in setups with managed identity, service principals etc. without having to use the CLI.

**Comment by andrefurlan-db** [comment]
Support for Azure AD OAuth has been added on #327

**Comment by AkhilGNair** [comment]
Just a note on @sdebruyn's answer
```
az account get-access-token --resource $env:DATABRICKS_RESOURCE_ID --query accessToken -otsv
```
also works, rather than hopping over to `jq`
