### ISSUE TITLE
Enable automated integration tests for all environments

### ISSUE THREAD

**Issue by susodapop** [databricks/dbt-databricks#290]
### Describe the feature

In #274 we enabled automated integration tests for 1/4 of our test profiles (in bold below):

1. **SQL warehouse**
2. SQL warehouse with UC
3. Interactive cluster
4. Interactive cluster with UC

We need to enable automated testing for the other three profiles. 

### Describe alternatives you've considered

This is required for certification with dbt.

### Additional context
 
See #286

### Who will this benefit?

This is required for certification with dbt.

### Are you interested in contributing this feature?

Yes!

**Comment by andrefurlan-db** [comment]
The vast majority of our code paths are common between SQL Warehouses and Interactive Clusters. Unity Catalog tests add support for 3 level namespaces and fine grain security.
