### ISSUE TITLE
add native `split_part` to the cross db utils

### ISSUE THREAD

**Issue by dave-connors-3** [databricks/dbt-databricks#299]
### Describe the feature

Right now, dbt offers native support for any cross-db macros, including split_part. The [implementation in dbt-spark right now](https://github.com/dbt-labs/dbt-spark/blob/main/dbt/include/spark/macros/utils/split_part.sql) is fairly complex, given that there's not native support for `split_part` in spark. This gets especially complex for [negative arguments to the function](https://github.com/dbt-labs/dbt-spark/pull/689), which relies on some heavy string parsing to properly translate a negative arg into the appropriate index in the array. Given that databricks [natively supports this function](https://docs.databricks.com/sql/language-manual/functions/split_part.html) including negative part_numbers, it may be a good idea to implement here to avoid this complex logic. 

### Describe alternatives you've considered
 Do nothing, inherit from dbt-spark

### Additional context
Please include any other relevant context here.

### Who will this benefit?

package maintainers like me!

### Are you interested in contributing this feature?

For sure

**Comment by dbeatty10** [comment]
[dbt-labs/dbt-spark #689](https://github.com/dbt-labs/dbt-spark/pull/689/files) added support for negative `part_number` argument to dbt-spark. Like @dave-connors-3 mentioned, dbt-databricks will just inherit this logic, so it is not strictly necessary to override it.

But providing a native implementation might be as simple as copy-pasting the logic from the [default implementation](https://github.com/dbt-labs/dbt-core/blob/a57fdf008e3dee69a9f15f0bae6c93c2f7577ff1/core/dbt/include/global_project/macros/utils/split_part.sql#L5-L13):

`dbt/include/databricks/macros/utils/split_part.sql`

```sql
{% macro databricks__split_part(string_text, delimiter_text, part_number) %}

    split_part(
        {{ string_text }},
        {{ delimiter_text }},
        {{ part_number }}
        )

{%- endmacro %}
```

Or just inherit the default from dbt-core:

```sql
{% macro databricks__split_part(string_text, delimiter_text, part_number) %}

    {{ dbt.default__split_part(string_text, delimiter_text, part_number) }}

{%- endmacro %}
```

### :warning: Caveat
I didn't check one way or the other if the semantics of [`split_part` in Databricks](https://docs.databricks.com/sql/language-manual/functions/split_part.html) would necessitate bifurcated logic like in [here](https://github.com/dbt-labs/dbt-core/blob/a57fdf008e3dee69a9f15f0bae6c93c2f7577ff1/plugins/postgres/dbt/include/postgres/macros/utils/split_part.sql#L4).

[This](https://github.com/databricks/dbt-databricks/blob/2edb61d59db024786eb0914d53f978d04597bffc/tests/functional/adapter/utils/test_utils.py#L146-L147) inherited test in dbt-databricks includes a negative test case as-of dbt-core v1.6, so it should catch cases where any new implementation is off.
