### ISSUE TITLE
dbt-databricks adapter plugin  inherits from the dbt-spark plugin

### ISSUE THREAD

**Issue by natarajanc-prodigygame** [databricks/dbt-databricks#32]
### Describe the feature

Teams using dbt-spark and dbt-labs/spark-utils intending to migrate to using dbt-databricks cant do so because adapter name is now `databricks` instead of spark, so macros that are prefixed with `spark__` won't automatically be picked up for use.

### Describe alternatives you've considered

The dbt-databricks adapter plugin depends on / inherits from the dbt-spark plugin. This would have the effect of telling dbt, "For adapter-dispatched macros, look for databricks__, then spark__, then default__

### Who will this benefit?
What kind of use case will this feature be useful for? Please be specific and provide examples, this will help us prioritize properly.

teams wanting to use dbt-databricks with dbt-labs/spark-utils macros

**Comment by thunter009** [comment]
+1 on this issue -- currently blocked from using dbt-databricks
