### ISSUE TITLE
Column reordering problem with the new `replace_where` inc. strategy

### ISSUE THREAD

**Issue by dejan** [databricks/dbt-databricks#334]
### Describe the bug
Using `replace_where` incremental strategy breaks when columns are reordered in the model.

### Steps To Reproduce
Create an incremental model with columns of different types (e.g. int and string) with `replace_where` strategy, run once and then change the column order in the model and run again. A typing error will appear.

For example:
```sql
{{
    config(
        partition_by = ['report_date'],
        materialized = 'incremental',
        incremental_strategy = 'replace_where',
        incremental_predicates = 'report_date = "2023-05-05"'
    )
}}

select
  "2023-05-05" as report_date,
  100 as amount
```

Swapping the order of the last two lines gives error:
```
17:30:16  Runtime Error in model clicks (models/data_platform/clicks.sql)
17:30:16    [CAST_INVALID_INPUT] The value '2023-05-05' of the type "STRING" cannot be cast to "INT" because it is malformed. Correct the value as per the syntax, or change its target type. Use `try_cast` to tolerate malformed input and return NULL instead. If necessary set "spark.sql.ansi.enabled" to "false" to bypass this error.
```

### Expected behavior
Columns ordering does not play a part with other strategies so it should not matter in this one as well. It looks like implementation suffers from the problem originating in [Spark's limitation of INSERT INTO](https://github.com/apache/spark/blob/1b54b014543801c98d86e6e1151c7b763f98cfde/sql/core/src/main/scala/org/apache/spark/sql/DataFrameWriter.scala#L395-L396C30):

> Unlike `saveAsTable`, `insertInto` ignores the column names and just uses position-based

The behaviour from the current implementation is surprising and potentially can go undetected when  swapped columns are of the same type.

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.4.6
  - latest:    1.5.0 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - databricks: 1.4.3 - Update available!
  - spark:      1.4.1 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```

**Comment by andrefurlan-db** [comment]
Thanks for filing this. I agree. Let me look into what I can do.

**Comment by benc-db** [comment]
Agree that this has potential to silently cause errors.  Not sure if we will be to able to fulfill the requested merge strategy if the columns are reordered, but at a minimum, we should alert the user rather than silently work incorrectly.
