### ISSUE TITLE
`make_temp_relation` uses default database/schema instead of `target.database` and `target.schema`

### ISSUE THREAD

**Issue by Maayan-s** [databricks/dbt-databricks#344]
Hi team, 
We use this method as part of our dbt package, and for Databricks users it fails as many of them run dbt with a user that doesn't have permission to write to the default database. 
This is also inconsistent with how other adapters implemented the method (using the target database and schema nad not just the identifier). 

[We solved it on our end](https://github.com/elementary-data/dbt-data-reliability/pull/348/files) but I believe you should consider changing this on the adapter as well. 

https://github.com/databricks/dbt-databricks/blob/4d6e1ad03c5ef2a1e7f2a949dadbf9f8f3b37ff9/dbt/include/databricks/macros/adapters.sql#L427

**Comment by benc-db** [comment]
@andrefurlan-db  thoughts on this?  PR is https://github.com/databricks/dbt-databricks/pull/345.  Seems reasonable to me.

**Comment by benc-db** [comment]
Apologies for the delay in response; I appreciate the detailed reasoning.

**Comment by benc-db** [comment]
Unfortunately this can't be fixed; Databricks does not allow us to qualify the name of a temporary view: https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-ddl-create-view.html

When you say you've solved it on your end, how did you solve it?

**Comment by benc-db** [comment]
Closing as unfixable until Databricks supports qualified names for temporary views.  Happy to reopen if you know of a work around to this issue.
