### ISSUE TITLE
Python Clusters not starting correctly: race conditions?

### ISSUE THREAD

**Issue by ewengillies** [databricks/dbt-databricks#347]
### Describe the bug
Hi, I'm experiencing an issue when running python models from terminated clusters.  Feels related to https://github.com/databricks/dbt-databricks/pull/306#issuecomment-1520405748 and #306 in general.  Tagging  for visibility since you've responded on the other thread.

I use python models in conjunction with SQL models (no surprise there) but I configure each python model to have its their own `http_path` so that I can run the python models in conjunction with the SQL models from a single `dbt run --target <sql_warehouse>` command.  So the top level "run" points at SQL and each python model points at python.

Some of the python models run, others experience an error like:
```
{'error': 'ClusterNotReadyException: Cluster <cluster_id> not currently ready for driver client (currently Pending)'}
```

### Steps To Reproduce
Not 100% sure, but I would say:

- Run `dbt run` against a SQL warehouse with python-model level `http_path`s pointing to an all purpose cluster.
- Ensure some SQL models run first.
- Ensure 5+ python models all get hit in the dag around the same time (within the window of terminated -> running, say 2 minutes).

### Expected behavior
I expect for the all purpose cluster to boot when it encounters the first python model and then for all other simultaneous models to realize its booting and wait until the cluster is ready.

### Screenshots and log output
See bug description.

### System information
**The output of `dbt --version`:**
core is 1.5.0
spark is 1.5.0
databricks is 1.5.0

**The operating system you're using:**

Linux

**The output of `python --version`:**
3.10.4

### Additional context

All the python models point to the same `http_path`.  This feels like a recipe for the race condition @susodapop described in #306 where by:

1.  the first python model to run gets a `TERMINATED` cluster and then runs [`start_cluster`](https://github.com/databricks/dbt-databricks/blob/main/dbt/adapters/databricks/python_submissions.py#LL262C9-L262C22) as intended, then
2. the second one sees that the cluster is neither [`TERMINATED` nor `TERMINATING`](https://github.com/databricks/dbt-databricks/blob/main/dbt/adapters/databricks/python_submissions.py#L210) and then skips the if statement, stumbles in to the [create context](https://github.com/databricks/dbt-databricks/blob/main/dbt/adapters/databricks/python_submissions.py#L215) call and dies a death a la: `Cluster <cluster_id> not currently ready for driver client (currently Pending)`.
3. This seems to be re-enforced by the fact that a quick search shows the "pending" status does not appear in any of the python code, so I'm guessing unhandled at the moment?

I think an elegant solution might be to shift the waiting part ([seen here](https://github.com/databricks/dbt-databricks/blob/main/dbt/adapters/databricks/python_submissions.py#L282-L298)) out of `DBContext.start_cluster` into its own function `DBContext.wait_for_running_cluster` and then call this in `DBContext.create` directly after (but outside) the `TERMINATED` conditional:

1. This adds at least one `get_cluster_status` call to each context creation, but that feels right since we need to know its `RUNNING` before context can be created.
2. This also delegates the "shared state" of the separate threads (is my cluster ready or not) to the API, which is easy to share amongst the threads. 
3. That said, I've only skimmed the code, could be the wrong approach. 

My work around for now is to boot the cluster at the start of the job in a separate API call.  This assumes the cluster doesn't auto-terminate before the python models run, which isn't great.

**Comment by ewengillies** [comment]
I'll make some debug logs for us to verify with as well.

**Comment by followingell** [comment]
_As a note I am also seeing this behavior, following._

**Comment by ValdarT** [comment]
Was this issue was addressed by [this PR](https://github.com/databricks/dbt-databricks/pull/461) or was that something else still?

**Comment by benc-db** [comment]
@ValdarT Good call; now that I reread this ticket, it sounds exactly like what I was trying to fix haha.  For everyone on this issue, please try 1.6.5 and let me know if you are still seeing this issue / reopen this ticket.  Closing as fixed for now.

**Comment by ValdarT** [comment]
Still running into this with dbt=1.6.3 and adapter: databricks=1.6.5
```
Error starting terminated cluster.
   b'{"error_code":"INVALID_STATE","message":"Cluster 0802-060324-ir9ydk9r is in unexpected state Pending.","details":[{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"CM_API_ERROR_SOURCE_CALLER_ERROR","domain":""}]}'
```

**Comment by ValdarT** [comment]
Yes, using a bunch of python models, 16 threads, `submission_method: all_purpose_cluster`. 2 python models were executed, all the rest failed with the `"error_code":"INVALID_STATE"`.

**Comment by Buxert** [comment]
@benc-db We are experiencing the same issue. Multiple python models are pointing to the same cluster. If you only run 1 model, you just get the following output:

`Databricks adapter: Waiting for cluster to be ready`

But if you run multiple models that are in the same folder, the first python model will start the cluster and keeps waiting until the cluster is started. The second, third etc.. python models will fail and give this output:

```
Runtime Error in model int_model (models/conformed/intermediates/int_model.py)
  Error starting terminated cluster.
   b'{"error_code":"INVALID_STATE","message":"Cluster <number> is in unexpected state Pending.","details":[{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"CM_API_ERROR_SOURCE_CALLER_ERROR","domain":""}]}'

```

Here is the part of the dbt.log:

```

[0m16:01:03.846612 [debug] [Thread-4 (]: Databricks adapter: Cluster <number> is not running. Attempting to restart.
[0m16:01:03.847970 [debug] [Thread-4 (]: Databricks adapter: Sending restart command for cluster id <number>
[0m16:01:03.849204 [debug] [Thread-3 (]: Databricks adapter: Cluster<number> is not running. Attempting to restart.
[0m16:01:03.850722 [debug] [Thread-3 (]: Databricks adapter: Sending restart command for cluster id <number>
[0m16:01:04.047103 [info ] [Thread-3 (]: Databricks adapter: Waiting for cluster to be ready
[0m16:01:04.063113 [debug] [Thread-4 (]: Timing info for model.transforming_silver.int_model2.py (execute): 16:01:03.373035 => 16:01:04.062527
[0m16:01:04.064116 [debug] [Thread-4 (]: Databricks adapter: DatabricksDBTConnection._release: name: model.transforming_silver.int_model2.py, thread: (442626, 140020681791168), compute: ``, acquire_release_count: 1, idle time: 12.55363130569458s
[0m16:01:04.069359 [debug] [Thread-4 (]: Runtime Error in model int_cost_center_node_structure (models/conformed/intermediates/int_model2.py)
  Error starting terminated cluster.
   b'{"error_code":"INVALID_STATE","message":"Cluster <number> is in unexpected state Pending.","details":[{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"CM_API_ERROR_SOURCE_CALLER_ERROR","domain":""}]}'
[0m16:01:04.071090 [debug] [Thread-4 (]: Databricks adapter: DatabricksDBTConnection._release: name: model.transforming_silver.int_model2, thread: (442626, 140020681791168), compute: ``, acquire_release_count: 0, idle time: 0.005917549133300781s
[0m16:01:04.071798 [debug] [Thread-4 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '60d0fd3d-a588-41ab-8bcf-2d79cbdf9f3c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5945b10f50>]}
[0m16:01:04.072420 [error] [Thread-4 (]: 2 of 2 ERROR creating python table model conformed.int_model2  [[31mERROR[0m in 0.74s]
[0m16:01:04.073012 [debug] [Thread-4 (]: Finished running node model.transforming_silver.int_model2
[0m16:02:40.775426 [debug] [Thread-3 (]: Databricks adapter: Cluster <number> is now running.
[0m16:02:40.775936 [info ] [Thread-3 (]: Databricks adapter: Waiting for cluster to be ready
[0m16:02:41.385135 [info ] [Thread-3 (]: Databricks adapter: Job submission response={'id': 'c901688aa1504c37b4341d87e6742725'}
[0m16:03:55.861842 [debug] [Thread-3 (]: Databricks adapter: No cursor was provided. Query ID not available.
[0m16:03:55.862929 [debug] [Thread-3 (]: Execution status: OK in 172.08999633789062 seconds
[0m16:03:55.880852 [info ] [Thread-3 (]: Ownership granted to dap-3-develop to the table int_model1
[0m16:03:55.881264 [debug] [Thread-3 (]: Using databricks connection "model.transforming_silver.int_model1.py"
[0m16:03:55.881548 [debug] [Thread-3 (]: On model.transforming_silver.int_model1: /* {"app": "dbt", "dbt_version": "1.7.7", "dbt_databricks_version": "1.7.3", "databricks_sql_connector_version": "2.9.3", "profile_name": "transforming_silver", "target_name": "lab", "node_id": "model.transforming_silver.int_model1"} */

        ALTER TABLE `catalog`.`schema`.`int_model1` OWNER TO `owner`
  
[0m16:03:56.390220 [debug] [Thread-3 (]: SQL status: OK in 0.5099999904632568 seconds
[0m16:03:56.392456 [debug] [Thread-3 (]: Timing info for model.transforming_silver.int_model1 (execute): 16:01:03.365525 => 16:03:56.392293
[0m16:03:56.392742 [debug] [Thread-3 (]: Databricks adapter: DatabricksDBTConnection._release: name: model.transforming_silver.int_model1, thread: (442626, 140020690183872), compute: ``, acquire_release_count: 1, idle time: 184.75430393218994s
[0m16:03:56.393241 [debug] [Thread-3 (]: Databricks adapter: DatabricksDBTConnection._release: name: model.transforming_silver.int_model1, thread: (442626, 140020690183872), compute: ``, acquire_release_count: 0, idle time: 0.0002288818359375s
[0m16:03:56.393540 [debug] [Thread-3 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '60d0fd3d-a588-41ab-8bcf-2d79cbdf9f3c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5945b9e410>]}
[0m16:03:56.393901 [info ] [Thread-3 (]: 1 of 2 OK created python table model conformed.int_account_node_structure ...... [[32mOK[0m in 173.06s]
[0m16:03:56.394280 [debug] [Thread-3 (]: Finished running node model.transforming_silver.int_account_node_structure
[0m16:03:56.397159 [debug] [MainThread]: Databricks adapter: Reusing DatabricksDBTConnection. name: master, thread: (442626, 140022583166208), compute: ``, acquire_release_count: 0, idle time: 173.07622003555298s
[0m16:03:56.397940 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection._acquire: name: master, thread: (442626, 140022583166208), compute: ``, acquire_release_count: 0, idle time: 173.07703566551208s
[0m16:03:56.398685 [debug] [MainThread]: Databricks adapter: Thread (442626, 140022583166208) using default compute resource.
[0m16:03:56.399479 [debug] [MainThread]: On master: ROLLBACK
[0m16:03:56.400279 [debug] [MainThread]: Opening a new connection, currently in state init
[0m16:03:56.509527 [debug] [MainThread]: Databricks adapter: NotImplemented: rollback
[0m16:03:56.510577 [debug] [MainThread]: Spark adapter: NotImplemented: add_begin_query
[0m16:03:56.511354 [debug] [MainThread]: Spark adapter: NotImplemented: commit
[0m16:03:56.512130 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection._release: name: master, thread: (442626, 140022583166208), compute: ``, acquire_release_count: 1, idle time: 173.19119572639465s
[0m16:03:56.513455 [debug] [MainThread]: Connection 'master' was properly closed.
[0m16:03:56.514158 [debug] [MainThread]: On master: ROLLBACK
[0m16:03:56.514787 [debug] [MainThread]: Databricks adapter: NotImplemented: rollback
[0m16:03:56.515346 [debug] [MainThread]: On master: Close

[0m16:03:56.792198 [info ] [MainThread]: 
[0m16:03:56.792928 [info ] [MainThread]: Finished running 2 table models in 0 hours 3 minutes and 6.20 seconds (186.20s).
[0m16:03:56.793810 [debug] [MainThread]: Command end result
[0m16:03:56.809581 [info ] [MainThread]: 
[0m16:03:56.809935 [info ] [MainThread]: [31mCompleted with 1 error and 0 warnings:[0m
[0m16:03:56.810178 [info ] [MainThread]: 
[0m16:03:56.810398 [error] [MainThread]:   Runtime Error in model int_cost_center_node_structure (models/conformed/intermediates/int_model2.py)
  Error starting terminated cluster.
   b'{"error_code":"INVALID_STATE","message":"Cluster <number> is in unexpected state Pending.","details":[{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"CM_API_ERROR_SOURCE_CALLER_ERROR","domain":""}]}'
[0m16:03:56.810621 [info ] [MainThread]: 
[0m16:03:56.810839 [info ] [MainThread]: Done. PASS=1 WARN=0 ERROR=1 SKIP=0 TOTAL=2
[0m16:03:56.811423 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 188.4372, "process_user_time": 5.018826, "process_kernel_time": 1.541808, "process_mem_max_rss": "230552", "process_out_blocks": "11312", "command_success": false, "process_in_blocks": "0"}
[0m16:03:56.811829 [debug] [MainThread]: Command `dbt run` failed at 16:03:56.811723 after 188.44 seconds
[0m16:03:56.812143 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f598724fbd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5988b3f3d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f598bbd9310>]}
[0m16:03:56.812428 [debug] [MainThread]: Flushing usage events

```

**Comment by benc-db** [comment]
@Buxert thanks for providing your error log, that is very helpful.  Once I clear my current plate, I'll dig into this.
