### ISSUE TITLE
Model Level Retry

### ISSUE THREAD

**Issue by matt-winkler** [databricks/dbt-databricks#356]
### Describe the feature
Ability to configure some number of retries for dbt models run via the adapter.

### Describe alternatives you've considered

- Re-running dbt jobs entirely, which isn't practical in a production setting.
- Overriding dbt job commands, which also isn't practical in a production setting.

### Additional context
This is particularly relevant when the situation below arises: 

```
Error while reading file ${path} It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.
```

running the SQL command for the dbt model again should resolve this.

### Who will this benefit?
Users running dbt-databricks in production.

### Are you interested in contributing this feature?
Potentially. Request some guidance from the maintainers on where this functionality should live.

**Comment by andrefurlan-db** [comment]
Do you mean this? You can already set retries for models, just add this to your profile.yaml. (dbt-cloud unfortunately does not expose this yet

```
        "connect_retries": 3,
        "connect_timeout": 5,
        "retry_all": True,
```

**Comment by matt-winkler** [comment]
@andrefurlan-db thanks so much! I wasn't aware of that.

**Comment by andrefurlan-db** [comment]
yeah, we are actively working on better documentation.
