### ISSUE TITLE
"Error connecting to server" when running dbt 1.5.2 from databricks workflow

### ISSUE THREAD

**Issue by henrikamnas** [databricks/dbt-databricks#358]
### Describe the bug
As of this morning, when running dbt from our databricks worklfows we are getting failures which seems to be related to connection issues. More specifically it looks like this:
![image](https://github.com/databricks/dbt-databricks/assets/17888601/45a143b8-7b12-46f7-a78e-40fc140ba327)

and when viewing the query in the databricks query history we get the below error:
Query could not be scheduled: BAD_REQUEST: Invalid SessionHandle: Session [01ee05f4-c035-152f-9002-79f97bbe0a89] is closed.

### Steps To Reproduce
Run dbt-databricks from a databricks workflow using version 1.5.2

### Expected behavior
For dbt to be able to run the query against the Databricks sql endpoint

### Screenshots and log output
![image](https://github.com/databricks/dbt-databricks/assets/17888601/9019bd69-a364-4a8d-8567-1faf6758622d)

### System information
**The output of `dbt --version`:**
![image](https://github.com/databricks/dbt-databricks/assets/17888601/8026379d-e762-442b-a0fc-84b13e234403)
**The operating system you're using:**
Databricks job-cluster

**The output of `python --version`:**
python version: 3.9.5

### Additional context
This is a great package! Let me know if I can provide any more details.

**Comment by Frunkh** [comment]
As of today we're getting the same errors.
![image](https://github.com/databricks/dbt-databricks/assets/2933557/a03ec5fd-ad2d-4d4b-9d13-c92f014e240a)


We're also getting them now with older versions of dbt and dbt-databricks.

**Comment by Frunkh** [comment]
We did a few more tests and concluded the following; dbt-databricks is always grabbing the latest and greatest of the databricks-sql-connector, even when we downgrade dbt-databricks. So, what we did was pin the databricks-sql-connector version at 2.5.2 straight in the requirements.txt file. And voila, no more problems!

From this, it seems pretty clear that the hiccup was hiding in the databricks-sql-connector package, especially since it was just updated last night.

**Comment by henrikamnas** [comment]
Great thank you! Are you able to pin the databricks-sql-connector version inside the datarbicks job as well?

**Comment by Frunkh** [comment]
> Great thank you! Are you able to pin the databricks-sql-connector version inside the datarbicks job as well?

Yes this is possible!
Within your databricks job configure a new dependent library like this:

![image](https://github.com/databricks/dbt-databricks/assets/2933557/50afdc44-617c-4950-9f68-343c0a408cba)

**Comment by henrikamnas** [comment]
Seems to work, thank you very much!

**Comment by andrefurlan-db** [comment]
Fix has been published. Version 1.5.3. Thanks again for the issue.
