### ISSUE TITLE
Databricks: Query has been timed out due to inactivity

### ISSUE THREAD

**Issue by patkearns10** [databricks/dbt-databricks#359]
### Describe the bug
A clear and concise description of what the bug is. What command did you run? What happened?

Pat from dbt Labs here!
This is not in relation to our company accounts.

We have seen a couple customers reach out to us about long running jobs in dbt and upon investigation seems like one of the models / threads will timeout and fail on Databricks side but we don’t receive notice on our end, so we keep running the job until it hits the job timeout (or 24 hours if they do not have a timeout set up).

This is particularly confusing to us because we don't receive word that it timed out and therefore do not Error out the job.

![databricks_timeout](https://github.com/databricks/dbt-databricks/assets/30663534/22489b11-8a42-4bfc-9631-dd800cb770ca)

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.
This seems to be sporadic, only happening sometimes, and seems to happen to create, update, and hook type statements.
The timeouts are oddly usually less than 60 seconds.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**The output of `dbt --version`:**
```
1.4.6 and 1.5.0
```

### Additional context

Collected affected IDs.
01edf77d-7a7b-1fab-a04a-3e572068f2a3
01edff96-b864-12e3-ac83-fd01c999ccbb 
01ee00f1-9a9f-118c-bd98-64d8f7aedb56
01edfede-7028-1c28-8eb7-e3446ab134c6
01edffb6-2103-1745-ba32-3fe67df11f7a
01ee00b7-dcdd-10f7-a139-e0a93791ef9a

We also opened up a support ticket:
Ticket Detail:
Ticket Number: #00331582
Subject: dbt <> Databricks Timeout Issue
Ticket URL: https://help.databricks.com/s/case/5008Y00002A5sWS
Unique TicketId: [ ref:_00D61JGc4._5008Y2A5sWS:ref ]

**Comment by andrefurlan-db** [comment]
Thanks. This is an issue in Databricks (not dbt-databricks) that we are actively working on. Latest version of the adapter has a workaround to prevent connection waiting forever. Updating to version 1.5.4 will mitigate the issue.

**Comment by andrefurlan-db** [comment]
Will close this issue as it is not a dbt-databricks issue. The fix is currently being rolled out in production on Databricks side.

**Comment by patkearns10** [comment]
Got it, thank you!

**Comment by az259259** [comment]
@andrefurlan-db - we are intermittently running same issues refreshing power bi. on databricks end error message is "Query has been timed out due to inactivity." exactly same as mentioned with dbt. appreciate your response.
