### ISSUE TITLE
Ability to set private index URL for Python packages on job clusters

### ISSUE THREAD

**Issue by casperdamen123** [databricks/dbt-databricks#362]
### Describe the feature
In order to import Python modules from a private artifactory, I need to be able to install packages on the Databricks cluster from a private index instead of pypi.

### Describe alternatives you've considered
There is no real alternative for automatically installing Python packages from a private index on a job cluster. The only alternative is to use an all purpose cluster and pre-configure the packages directly on the cluster.

### Who will this benefit?
Users running Python models in production and leveraging shared functionality from private artifactory's. 

### Are you interested in contributing this feature?
Yes, I already have a branch that fixes this issue and tested it.

```  
# Private index URL or default
index_url = self.parsed_model["config"].get("index_url", "https://pypi.org/simple")

for package in packages:
   libraries.append({"pypi": {"package": package, "repo": index_url}})
```

**Comment by andrefurlan-db** [comment]
@susodapop , can you help @casperdamen123 with this? He just needs the contributing guide

**Comment by susodapop** [comment]
Yes 100% @andrefurlan-db 

@casperdamen123 I've drafted an up-to-date set of instructions for developing the repository and making pull requests, running unit tests locally etc. But the basics are super simple:

1. Fork this repository
2. Make your change
3. Open a pull request

Don't worry about running the integration tests just yet. We have dedicated environments for this so you don't need to incur any cloud costs to run them. Please ping me on this issue if you have any trouble with it.

**Comment by casperdamen123** [comment]
@susodapop, thanks for the elaboration!

I've opened the pull request.

**Comment by casperdamen123** [comment]
@susodapop, opened the pull request #367 

Do you have any view on how long it would take to review this relative small change?
