### ISSUE TITLE
dbt init gives error: Error: Invalid value for '--warn-error-options': Cannot load YAML from type <class 'dbt.helper_types.WarnErrorOptions'>

### ISSUE THREAD

**Issue by NielsHoogeveen1990** [databricks/dbt-databricks#383]
### Describe the bug
A clear and concise description of what the bug is. What command did you run? What happened?

When I create a venv and pip install dbt-databricks and I do: dbt init xxx
I get the following error:

`Error: Invalid value for '--warn-error-options': Cannot load YAML from type <class 'dbt.helper_types.WarnErrorOptions'>`

### Steps To Reproduce
1. Create venv with Python 3.9
2. Activate venv
3. Pip install dbt-databricks
4. Create dbt project with dbt init

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.5.2
  - latest:    1.5.2 - Up to date!

Plugins:
  - databricks: 1.5.4 - Up to date!
  - spark:      1.5.0 - Up to date!
```

**The operating system you're using:**
MacOS

**The output of `python --version`:**
Python 3.9.16

**Comment by ulisesojeda** [comment]
Use Python 3.7.x instead
