### ISSUE TITLE
Cannot use `is_incremental()` to programatically set `incremental_predicates`

### ISSUE THREAD

**Issue by garfieldthesam** [databricks/dbt-databricks#387]
### Describe the bug

I need to use Jinja to programmatically define a string to use for the `incremental_predicates` configuration depending on whether the model is run incrementally. The `replace_where` statement executed in Spark SQL does not accurately reflect whether `{{ is_incremental() }}` evaluates to `True` or `False`.

I am trying to reproduce a pattern I used extensively before migrating from Bigquery to Databricks. The Bigquery pattern used the `insert_overwrite` `incremental_strategy`, but we have to use `replace_where` in our Databricks repository because the data are not partitioned by date by default.

We have this macro which is designed to:
- If `start_date` and `end_date` are passed when issuing a `dbt run` CLI command, the query is filtered between `start_date` and `end_date`
- If they are not passed and it's an incremental run, the query is filtered over the last X number of days where X is a variable called `backfill_days`
- If they are not passed and it's not an incremental run, the query is filtered to all dates before today

```
{% macro incremental_variable_filter(partition_col, backfill_days=3) %}

    {% if is_incremental() and var("end_date", "3000-01-01") == "3000-01-01" and var("start_date", "3000-01-01") %}
        date({{ partition_col }}) between date_sub(current_date(), {{ backfill_days }}) 
            and current_date()
    {% elif not is_incremental() and var("end_date", "3000-01-01") == "3000-01-01" and var("start_date", "3000-01-01") %}
        date({{ partition_col }}) <= current_date()
    {% else %}
        date({{ partition_col }}) between '{{ var("start_date", "3000-01-01") }}'
                                      and '{{ var("end_date",   "3000-01-01") }}'
    {% endif %}

{% endmacro %}
```

We have dbt models that follow this pattern. Here's an imaginary file called `model.sql`:
```
{% set backfill_days = 1 %}

{% set start_date = var("start_date", "3000-01-01") %}
{% set end_date = var("end_date", "3000-01-01") %}

{% if is_incremental() and start_date == "3000-01-01" and end_date == "3000-01-01" %}
    {% set incremental_predicates_string = "datestamp between date_sub(current_date(), " + backfill_days|string + ") and current_date()" %}
{% elif not is_incremental() and start_date == "3000-01-01" and end_date == "3000-01-01" %}
    {% set incremental_predicates_string = "datestamp <= current_date()" %}
{% else %}
    {% set incremental_predicates_string = "datestamp between '" + start_date|string + "' and '" + end_date|string +"'" %}
{% endif %}

{{
    config(
        materialized = "incremental",
        incremental_strategy = "replace_where",
        incremental_predicates = "{incremental_predicates_string}".format(incremental_predicates_string = incremental_predicates_string),
    )
}}

select
    datestamp,
    '{{ start_date }}' as start_date,
    '{{ end_date }}' as end_date,
    '{{ is_incremental() }}' as is_incremental
from {{ source("source", "source_table") }}
where {{ incremental_variable_filter('datestamp', backfill_days) }}
limit 100 
```

When I perform a full refresh with `dbt run -s model -f` the Spark SQL code executed matches what is expected:
```
create
or replace table `dev`.`my_dev_schema_name`.`model` using delta comment '' as
select
  datestamp,
  '3000-01-01' as start_date,
  '3000-01-01' as end_date,
  'False' as is_incremental
from source_table
where
  date(datestamp) <= current_date()
limit
  100
```

But when we start an incremental run using `dbt run -s model` the code does not match what is expected:
First this statement runs, with the expected `where` clause:
```
create temporary view `model__dbt_tmp` as
select
  datestamp,
  '3000-01-01' as start_date,
  '3000-01-01' as end_date,
  'True' as is_incremental
from source_table
where
  date(datestamp) between date_sub(current_date(), 1)
  and current_date()
limit
  100
```

Then this statement runs with the incorrect `replace where` clause (since `is_incremental()` evaluates to `True`):
```
insert into
  `dev`.`my_dev_schema_name`.`model` replace
where
  datestamp <= current_date() table `model__dbt_tmp`
```

The executed SQL does match what is expected, however, when `start_date` and `end_date` are passed in the CLI. Eg. `dbt run -s model  --vars '{"start_date": "2023-07-01", "end_date": "2023-07-03"}'` results in these two statements:

Temp view:
```
create temporary view `model__dbt_tmp` as
select
  datestamp,
  '2023-07-01' as start_date,
  '2023-07-03' as end_date,
  'True' as is_incremental
from source_table
where
  -- TODO: change to backfill up to current_date
  date(datestamp) between '2023-07-01'
  and '2023-07-03'
limit
  100
```

Insert:
```
insert into
  `dev`.`my_dev_schema_name`.`model` replace
where
  datestamp between '2023-07-01'
  and '2023-07-03' table `model__dbt_tmp`
```

### Steps To Reproduce
Create a dbt project using the code samples above. Test with the `dbt` CLI commands above.

### Expected behavior
When the command `dbt run -s model` is run the the `insert` statement should look like this:
```
insert into
  `dev`.`my_dev_schema_name`.`model` replace
where
  date(datestamp) between date_sub(current_date(), 1)
  and current_date() table `model__dbt_tmp`
```

### Screenshots and log output
N/A
### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.5.0
  - latest:    1.5.2 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - databricks: 1.5.1   - Update available!
  - bigquery:   1.5.0   - Update available!
  - postgres:   1.5.0a1 - Update available!
  - spark:      1.5.0   - Up to date!
 ```

**The operating system you're using:**
Ventura 13.1 

**The output of `python --version`:**
Python 3.9.6

### Additional context
N/A

**Comment by benc-db** [comment]
Is there something preventing you from partitioning by date?  Based on your pattern here, it seems like it would make things much easier.  This adapter does not control when is_incremental becomes defined, and my guess is that it is not defined prior to reading the config for the table.

**Comment by benc-db** [comment]
That is an issue that only dbt-core can address.  Our adapter does not determine when is_incremental is defined.
