### ISSUE TITLE
 AnalysisException: org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.UnsupportedOperationException: getTables with TableType is not supported

### ISSUE THREAD

**Issue by amihaygil** [databricks/dbt-databricks#394]
### Describe the bug
use dbt-databrick adapater against hive compitable catalog (aws glue) failed when do dbt run
### Steps To Reproduce
upgrade to lastest version of dbt-databricks adapter 
run any model 
code is failing when starting  on show views in  ... on 

 AnalysisException: org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.UnsupportedOperationException: getTables with TableType is not supported

### Expected behavior
until it is fixed an option to bypass check show views step

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
```
❯ dbt --version
Core:
  - installed: 1.5.3
  - latest:    1.5.3 - Up to date!

Plugins:
  - databricks: 1.5.5 - Up to date!
  - spark:      1.5.0 - Up to date!

```

**The operating system you're using:**
n/a
**The output of `python --version`:**
n/a

**Comment by susodapop** [comment]
The error is coming from Databricks compute not from `dbt-databricks`. I'm investigating. Looks like we've seen it before with glue catalog enabled. More details as soon as I have them.

**Comment by amihaygil** [comment]
Indeed , this is related to spark <--> Glue catalog , btw I've tried to query the Glue catalog using Athena and it worked fine.
i would be nice as a temporary solution to have a w/o to bypass the 'view' check

**Comment by benc-db** [comment]
Is this still an issue?
