### ISSUE TITLE
question: does databricks_copy_into macro supports Azure?

### ISSUE THREAD

**Issue by csimplestring** [databricks/dbt-databricks#406]
Hi 

as the document said, we can use databricks_copy_into macro for S3, does it support other cloud storage like Azure?
Also, what is the difference with dbt-external-table? I think they are doing the same thing: load files from external location to databricks. Please correct me if I am wrong.

**Comment by benc-db** [comment]
Sorry for delay in answering this question.  Yes, it's supported; unfortunately our local docs assume AWS, but we test against Azure.
