### ISSUE TITLE
Liquid Clustering configuration for Python-based models

### ISSUE THREAD

**Issue by ammarchalifah** [databricks/dbt-databricks#411]
### Describe the feature
Similar to Liquid Clustering for SQL-based Delta tables in this [PR](https://github.com/databricks/dbt-databricks/pull/398), similar functionality should also be implemented for Python-based model. Currently Liquid Clustering doesn't have stable API in Python, so the implementation of this feature request might wait for that.

### Describe alternatives you've considered
-

### Additional context
-

### Who will this benefit?
Databricks customer who wish to use Liquid Clustering & dbt.

### Are you interested in contributing this feature?
Yes

**Comment by benc-db** [comment]
Just updating to note that this work (the python support) is waiting on PySpark to support this feature.  Until then not much I can do, since liquid clustering needs to be declared as part of table create.
