### ISSUE TITLE
Ability to set TBLPROPERTIES from model metadata

### ISSUE THREAD

**Issue by bilalaslamseattle** [databricks/dbt-databricks#42]
### Describe the feature
[TBLPROPERTIES](https://docs.databricks.com/spark/latest/spark-sql/language-manual/sql-ref-syntax-ddl-create-table-like.html) are key-value metadata on tables in Databricks. This feature adds the ability to set these properties from model metadata.

### Describe alternatives you've considered
An alternative is run SQL to do this.

### Who will this benefit?
Anyone who likes to track metadata e.g. owners, teams, etc. on tables

### Are you interested in contributing this feature?
Sure!

**Comment by superdupershant** [comment]
duplices #33
