### ISSUE TITLE
Disable log output of databricks-sql-connector in cli

### ISSUE THREAD

**Issue by leo-schick** [databricks/dbt-databricks#432]
### Describe the feature

Since version 1.5.5 of this adapter, the log output of `databricks-sql-connector` is printed to the console:

![image](https://github.com/databricks/dbt-databricks/assets/67712864/7c9c4275-f1db-43de-a7fd-e3fab2973041)
![image](https://github.com/databricks/dbt-databricks/assets/67712864/443e3cfd-5830-4d07-8657-7599d79cec11)

I discovered this now since I upgraded from 1.4.6 to 1.6.1. I have multiple non-technical people which I like to introduce to dbt but this output now looks cumbersome and hard to understand for non-technical people. It might have its reason, but I see it more as disturbing when I not actually search for a bug ...

Can this be moved into the dbt log file and removed from the console output? I think this is against what dbt stands for: a easy to use and understand piece of software. This log just disturbes this which makes it hard for me to train non-technical people for it.

### Describe alternatives you've considered
Maybe add an opt-in or opt-out option for this which can be set via an environment variable?

### Additional context
dbt-core 1.6.1
dbt-databricks 1.6.1

### Who will this benefit?
Everybody using this provider and read the cli logs: It gets easier to understand

### Are you interested in contributing this feature?
No. I don't know how.

**Comment by weberdavidvw** [comment]
I am also affected by this issue.
When running several models and hooks in dbt, the cli is already filled with a lot of information - especially for non-tech users. While I do value connection logging, it would be great to either

- introduce logging levels (which IMO is a bigger topic connected with dbt-core)
- give the option to log into a file
- and giving the option to deactivate the logging of the adapter

Happy to support where possible!

**Comment by weberdavid** [comment]
I am also affected by this issue.
When running several models and hooks in dbt, the cli is already filled with a lot of information - especially for non-tech users. While I do value connection logging, it would be great to either

- introduce logging levels (which IMO is a bigger topic connected with dbt-core)
- give the option to log into a file
- and giving the option to deactivate the logging of the adapter

Happy to support where possible!
