### ISSUE TITLE
Include node_info in SQLQueryStatus

### ISSUE THREAD

**Issue by colin-rogers-dbt** [databricks/dbt-databricks#452]
### Describe the feature
dbt-core `SQLQueryStatus` includes an optional `node_info` field. Currently dbt-databricks does not populate it when firing [the event](https://github.com/databricks/dbt-databricks/blob/2579a20ad486414169f6616b9e82cb5845238e6b/dbt/adapters/databricks/connections.py#L813). Doing so makes it easier for consumers to utilize the logs.

### Additional context
dbt-core example: https://github.com/dbt-labs/dbt-core/blob/d91265411061463b42d6f4d6d94e094a42a96d2b/core/dbt/adapters/sql/connections.py#L83

### Who will this benefit?
What kind of use case will this feature be useful for? Please be specific and provide examples, this will help us prioritize properly.

### Are you interested in contributing this feature?
Let us know if you want to write some code, and how we can help.

**Comment by colin-rogers-dbt** [comment]
@benc-db we should reopen this issue, looks like me prior fix missed `SQLQuery` events

**Comment by benc-db** [comment]
@colin-rogers-dbt I believe we can reclose now, with #494 right?
