### ISSUE TITLE
Too many redirects - Response Error when running "dbt seed"

### ISSUE THREAD

**Issue by BharathMonash** [databricks/dbt-databricks#456]
### Describe the bug
Running a `dbt` job on `databricks workflows` with a custom profile. The job exits with `exit code 2` with an error message shown below (too many redirects) when running `dbt seed`. I'm running couple of other `dbt` commands before running `dbt seed` and they run just fine - `dbt debug` gives a proper out with all tests passing but still fails with database error when running `dbt seed`.

Sreenshots provided below

### Steps To Reproduce
Regular dbt workflow setup with custom profile as mentioned in the docs.

### Expected behavior
If I issue the same command (`dbt seed`) locally with my personal access token - it works but fails when running as a part of a workflow. I expect it to just run normally without failing.

### Screenshots and log output
`dbt debug` output log:
![Screenshot 2023-09-22 at 11 13 12 am](https://github.com/databricks/dbt-databricks/assets/70929739/1f6ef396-e927-4491-9df5-d8eaef731d3f)

`dbt seed` output log:
![Screenshot 2023-09-22 at 11 15 38 am](https://github.com/databricks/dbt-databricks/assets/70929739/e8136adb-ba17-4281-8f37-f02155baa0c9)

### System information
dbt version = `1.6.2`
dbt-databricks adapter version = `1.6.4`
operating system = `Linux`
Python version = `3.9`

### Additional context
If I issue the same command (`dbt seed`) locally with my personal access token - it works but fails when running as a part of a workflow. Requesting guidance on how I can avoid hitting this error. Any help is appreciated sinc the error message doesn't really tell us a lot. 

I have tried looking for this error within the adapter but looks like any database error message is just relayed by the adapter.

**Comment by benc-db** [comment]
Can you share what your profile for the workflow looks like (redacting any secrets)?

**Comment by BharathMonash** [comment]
@benc-db, that's how my `profiles.yml` looks like - using PAT instead of auto-generated token.
![Screenshot 2023-09-26 at 11 50 27 am](https://github.com/databricks/dbt-databricks/assets/70929739/7844f4fb-cdd5-4af6-8b1e-67ecf7117dde)

**Comment by benc-db** [comment]
I've brought your issue to the attention of the Jobs team; will update here when we figure something out.

**Comment by BharathMonash** [comment]
So @benc-db, I dug deeper and found out that the query is not getting queued/submitted to the warehouse cluster. While running `dbt debug`, dbt submits `select 1 as id` to the cluster to check connectivity which I can see in the query history of the SQL cluster but the `dbt seed` query is not reflecting in the query history or the queue.

Also in the job cluster logs I can see that it errors out with `ModuleNotFoundError: Couldn't find module 'dbt.main'`

Not sure whats causing this, any help would be appreciated. TIA!

**Comment by benc-db** [comment]
> @benc-db, that's how my profiles.yml looks like - using PAT instead of auto-generated token.

Could you explain a little bit more by what you mean here?  Is this line present in your profile that you're using in the workflows:

```
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"
```

**Comment by benc-db** [comment]
> Also in the job cluster logs I can see that it errors out with ModuleNotFoundError: Couldn't find module 'dbt.main'

Would mind sharing the lines around this error?

**Comment by BharathMonash** [comment]
> > Also in the job cluster logs I can see that it errors out with ModuleNotFoundError: Couldn't find module 'dbt.main'
> 
> Would mind sharing the lines around this error?

@benc-db - log4j output for lines where it shows ERROR

![Screenshot 2023-10-03 at 2 47 37 pm](https://github.com/databricks/dbt-databricks/assets/70929739/69c9631b-367c-46be-b77b-dffde95aacad)
![Screenshot 2023-10-03 at 2 48 14 pm](https://github.com/databricks/dbt-databricks/assets/70929739/cbc607e5-3e76-4aef-91b1-627195d71c23)

**Comment by BharathMonash** [comment]
> > @benc-db, that's how my profiles.yml looks like - using PAT instead of auto-generated token.
> 
> Could you explain a little bit more by what you mean here? Is this line present in your profile that you're using in the workflows:
> 
> ```
>       token: "{{ env_var('DBT_ACCESS_TOKEN') }}"
> ```

So `DBT_ACCESS_TOKEN` is the token that the cli cluster used to authenticate against the warehouse cluster right?
Yes, it is present in the profile for workflows job :)

**Comment by benc-db** [comment]
So the reason I'm asking is that I'm wondering if the token is actually getting a value.  If token is not defined, we try to do OAuth, which could result in redirects.  Could you try setting auth_type: "token" and see if you get the same or a different error?

**Comment by BharathMonash** [comment]
@benc-db - I tried adding `auth_type: "token"` - still getting the same error. 

Also, I can confirm that the PAT is getting passed properly, I ran `"dbt run-operation --args '{variable_name: DBT_ACCESS_TOKEN}' debug_env_var"` as one of the commands and I can see the PAT being passed properly.

Do you think I need to pin the `databricks-sql-connector` to a specific version and try? - if so which version do you recommend?

**Comment by benc-db** [comment]
You could try pinning to 1.6.5 of dbt-databricks, which would put you on the newest databricks-sql-connector version as well.

**Comment by BharathMonash** [comment]
I updated the version of dbt-databricks to 1.6.5 - still the same error.

**Comment by benc-db** [comment]
I'll bring back to the workflow team, thanks for verifying.

**Comment by benc-db** [comment]
Ok, so after confirming with Jobs/Workflow team, our next idea is that the 'host' entry is using a 'vanity url', and trying to connect from inside the workspace to that url is causing problems.  Could you please verify that this is _exactly_ what is listed on your warehouse where it says Server hostname?

**Comment by BharathMonash** [comment]
I fixed it, It wasnt looking at the correct profiles directory for some reason - It was still looking for auto generated profile even when i was using a cutom profile.

Closing the issue, thanks @benc-db
