### ISSUE TITLE
databricks sdk security issues with requests 

### ISSUE THREAD

**Issue by srggrs** [databricks/dbt-databricks#457]
### Describe the bug
Seems that `databricks-sdk` dependency is stuck at 0.1.7, which lock `requests` version to requests<2.29.0 and >=2.28.1.
Our security bot identified issues with such requests version, see https://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q

### Wanted outcome
would be possible to upgrade the sdk to a later version that has not issues with regard the requests package?

### System information
**The output of `dbt --version`:**
```
dbt 1.5.6
dbt databricks: 1.5.5
```

**The operating system you're using:**
Linux - Ubuntu
**The output of `python --version`:**
Python 3.9.18

**Comment by benc-db** [comment]
Thanks for bringing this to our attention, will investigate.

**Comment by srggrs** [comment]
Thank @benc-db for that, would be possible to do an incremental release for the 1.5 version, ie 1.5.6 with this? Thanks!

**Comment by benc-db** [comment]
@srggrs probably, but what is blocking you from moving to 1.6.x?

**Comment by srggrs** [comment]
I think we can migrate to dbt 1.6, but I think we need to check compatibility with the dagster version that we are using, as that is our orchestration tool

**Comment by benc-db** [comment]
I'm working on a backport release this morning.  I just would like to understand if there's anything in the dbt-databricks library that is preventing adoption.  I understand if there are limitations with your orchestration layer :).

**Comment by srggrs** [comment]
I can actually confirm the orchestration layer is not an issue and I tried to migrate to dbt 1.6 to use this fix in dbt-databricks library but I encountered the issue described in #466

**Comment by srggrs** [comment]
@benc-db thank you so much for fixing this and the url_index issue #466 . Now my problem is that I can't adopt dbt-databricks 1.5.6 and neither the 1.6.5 (both requires databricks-sdk==0.9.0) as `dagster-databricks` is locked to use `databricks-sdk` < 0.9. Is there anyway you can loose this requirement? Cheers
