### ISSUE TITLE
Installing custom repository pushed to AWS breaks

### ISSUE THREAD

**Issue by srggrs** [databricks/dbt-databricks#466]
### Describe the bug
When updating from dbt v1.5.4 and dbt-databricks v1.5.5 to dbt v1.6.4 and dbt-databricks v1.6.5 suddenly our python dbt models breaks due to an issue with the installation of a private python package that we regularly push to AWS code artifact.

### Steps To Reproduce
1 - create a python package even a simple one that has no functions
2 - publish the package to AWS code artifact
3 - create a python dbt model with `dbt.config(packages=["< my aws private package name >==< version >"])`
4 - run the python model using Databricks Job config so need to set up cluster and credentials

### Expected behavior
Package should install correctly. AWS references are setup correctly using a well tested init script. In fact if removing the `dbt.config(packages=["< my aws private package name >==< version >"])` and installing the package with a subprocess, by including these lines in the dbt model
```python
from subprocess import run

def model(dbt, session):
    data = run(
        "pip install < my aws private package name >==< version >",
        capture_output=True,
        shell=True,
        text=True
    )
    print(data.stdout)
    print(data.stderr)
```
the package is installed from the private repo with no issues.

### Screenshots and log output
![image](https://github.com/databricks/dbt-databricks/assets/34258464/b46a5f2b-eb49-407d-80f3-ec0b1867f665)

### System information
```bash
06:03:25  Running with dbt=1.6.4
06:03:25  Registered adapter: databricks=1.6.5
```
**The operating system you're using:**
Ubuntu

**The output of `python --version`:**
Python 3.9.18

### Additional context
Can see that a `index_url` config has been added in this #449 but not sure how to set that up with AWS private repos. Perhaps I need to use something like `https://vpce-xxxxx.api.codeartifact.us-east-1.vpce.amazonaws.com` as per https://aws.amazon.com/blogs/machine-learning/private-package-installation-in-amazon-sagemaker-running-in-internet-free-mode/ 
?

**Comment by benc-db** [comment]
Could you give a little more details on your previous process?  If you are installing separately with a setup script, I would think you just need to import the library here, rather that trying to use the package config.

**Comment by benc-db** [comment]
dbt.config(packages=...) to the best of my understanding is only used to specify the libraries parameter on the call we make to schedule a job run.  This parameter is explicitly for installing libraries; I believe it worked for you in the past because it found a matching library in the cache so that it didn't try to install again.  Since the artifact is private, if it didn't find it in the cache, I'm fairly sure you would have failed with the same error you're seeing now.  So, I believe just getting rid of this config line should get you the behavior you expect, since you are installing the library outside of the model definition.

**Comment by srggrs** [comment]
Sorry I meant to say that we configure the private repo in AWS code artifacts using their instructions (see [this link](https://docs.aws.amazon.com/codeartifact/latest/ug/python-configure-pip.html#python-configure-pip-login)). That modify the pip configs 
> The login command will configure pip for use with CodeArtifact by editing ~/.config/pip/pip.conf to set the index-url to the repository specified by the --repository option.

So the package was never cached and every time a job was submitted the init script is installing that pip configuration.

Adding the package in  `dbt.config(packages=...)` was working, but since you added that `index_url` it does not work anymore, even though that index url is save in pip config.

**Comment by benc-db** [comment]
@srggrs my plan is to check if index_url is defined, and if not, revert to the previous behavior.  Will be in the next release, which I will get out this week.

**Comment by srggrs** [comment]
thx man much appreciated!

**Comment by srggrs** [comment]
hi @benc-db I am getting this error again. I am using `dbt-databricks 1.6.4` with the DBR 13.3 but not with the DBR 11.3
