### ISSUE TITLE
Unable to upgrade to latest due to incompatibility with dagster_databricks package

### ISSUE THREAD

**Issue by srggrs** [databricks/dbt-databricks#482]
I started looking at upgrading to latest version of this due to the security issue posted in #457 but when the new release has been made, the requirement `databricks-sdk` jumped from 0.1.7 to 0.9.0 and that clash with our dagster requirements that is <0.9 (in the latest version, see https://github.com/dagster-io/dagster/blob/791ee08c4d4e173b3d861c3410070783453ba435/python_modules/libraries/dagster-databricks/setup.py#L41C70-L41C70) and we are not even using the latest but we could upgrade.

@benc-db thank you so much for fixing #457 and #466 but I still can't upgrade due to the incompatibilities with `dagster-databricks`. This happend for both dbt-databricks 1.6.6 as well as 1.5.6.

Would it possible to do an intermediate release to enable compatibilities with other packages?

Thank you!

**Comment by srggrs** [comment]
I wish but no unfortunately! I meant our pinned version of Dagster (1.4.12). I am working towards upgrading to the latest (>1.5) but still the dagster-databricks requirements clash with dbt-databricks requirements on the databricks-sdk package...

**Comment by benc-db** [comment]
I recommend filing a ticket with them to remove the dependency block.  I don't like the idea of releasing a newer version of dbt-databricks in order to downgrade requirements.
