### ISSUE TITLE
Malformed Request error - Simba version not supported

### ISSUE THREAD

**Issue by kdazzle** [databricks/dbt-databricks#485]
### Describe the bug

This error pops up whenever I try to grant permissions on a streaming table or materialized view. I figured my local env was wrong, but it happens on dbt cloud, as well. It happens whether or not I'm running dbt 1.6.6 or dbt-databricks 1.7. For some reason, a full refresh is fine.

> Error during request to server: MALFORMED_REQUEST: Client dbt-databricks/1.6.6 is not supported for SQL warehouses.SimbaJDBCDriver 2.6.14, SimbaODBCDriver 2.6.15 or above is required.

I've upgraded my simba version locally but the error still happens. I would guess there's something dumb that I'm missing?

```
$ pkgutil --info com.simba.sparkodbc
package-id: com.simba.sparkodbc
version: 2.7.5
volume: /
location: 
install-time: 1698075844
```

### Steps To Reproduce
Try to grant permissions when doing a REFRESH on a streaming table or materialized view

### Expected behavior
The permissions would get granted

### Screenshots and log output
See above. Also, for 1.7:

> MALFORMED_REQUEST: Client dbt-databricks/1.7.0rc1 is not supported for SQL warehouses.SimbaJDBCDriver 2.6.14, SimbaODBCDriver 2.6.15 or above is required.

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.7.0-rc1
  - latest:    1.6.6     - Ahead of latest version!

Plugins:
  - databricks: 1.7.0rc1 - Ahead of latest version!
  - spark:      1.7.0rc1 - Ahead of latest version!
```

**The operating system you're using:** OSX

**The output of `python --version`:** Python 3.9.11

**Comment by benc-db** [comment]
Historically when we've seen this, it meant that the workspace was not set up correctly for MV/ST (i.e. not in the public preview program, and without serverless SQL setup on the workspace).  Can you verify that your workspace has serverless SQL enabled?

**Comment by kdazzle** [comment]
Oh interesting. Yeah, we're in the public preview program (the tables are being created) and everything is being executed on a Serverless SQL warehouse or a serverless photon cluster for those streaming tables. It's just the grants for some reason. 

Maybe there's something else missing.

**Comment by benc-db** [comment]
Can you work with your Databricks contact to get a ticket filed with your logs?  Then I can get more attention on this issue from the MV side.  Thanks.

**Comment by kdazzle** [comment]
Yeah, definitely. Thanks for the help!

**Comment by benc-db** [comment]
We've identified the source of this issue, and are working on it.  Thanks for the bug report.

**Comment by kdazzle** [comment]
That's awesome - thank you!

**Comment by benc-db** [comment]
Fix will be rolling out this week/early next week (it's server side).  Please let me know if you still see this error next week.

**Comment by benc-db** [comment]
Should be fixed.  Reopen if you still see this.

**Comment by kdazzle** [comment]
Yeah it's been working great over the last month. Thanks Ben!
