### ISSUE TITLE
Import warnings when running DBT as a package on Databricks 13.3LTS

### ISSUE THREAD

**Issue by thijs-nijhuis-shell** [databricks/dbt-databricks#497]
### Describe the bug
Executing dbt as a Python package triggers about 200 import warnings when ran on Databricks Runtime 13.3 but not on 12.2. The warnings are all the same: `<frozen importlib._bootstrap>:914: ImportWarning: ImportHookFinder.find_spec() not found; falling back to find_module()`. The warning does not popup when running the python code locally either. 
The warning also appear when installing dbt-core instead of dbt-databricks but since it only happens when when running on Databricks clusters, I think it makes sense to post it here.

### Steps To Reproduce
Add a python file to your Databricks workspace and add this code. Run it on a Databricks cluster with 13.3LTS runtime (Shared or Single) and pre-install dbt-core 1.6.6 or dbt-databricks 1.6.6. 
```python
print("Starting")

from dbt.cli.main import dbtRunner

dbt = dbtRunner()

print("The End")
``` 
If you want to run the script a second time, you first need to 'detach & attach' otherwise the warnings won't show up.

As a workaround, I tried suppressing the warnings using `warnings.filterwarnings(action="ignore", category=ImportWarning)` but this doesn't work. I can set the action to error (which does raise the warnings to exception) and capture it in a `try...except` but than the package is not imported.

### Expected behavior
ImportWarnings are not shown at runtime.

### Screenshots and log output
When running the provided python script, the output will look like this:
```
Starting
<frozen importlib._bootstrap>:914: ImportWarning: ImportHookFinder.find_spec() not found; falling back to find_module()
...<<this exact warning repeats almost 200 times>>...
<frozen importlib._bootstrap>:914: ImportWarning: ImportHookFinder.find_spec() not found; falling back to find_module()
The End
``` 
### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.6.6
  - latest:    1.6.6 - Up to date!

Plugins:
  - spark:      1.6.0 - Up to date!
  - databricks: 1.6.6 - Up to date!
```

**The operating system you're using:**
Running on Databricks shared clusters with runtime 13.3LTS

**The output of `python --version`:**
When running on 13.3LTS: Python 3.10.12
When running on 12.2LTS: Python 3.9.5

Since this 'Find_spec' warning is introduced in python 3.10, this explain why it doesn't show up on 12.2 but it does happen on 13.3.

### Additional context
This issue was also discussed as a 'side'-issue over here: https://github.com/dbt-labs/dbt-core/issues/7828 . We found that older versions of `newrelic` or `wrapt` might be causing this issue but both are not installed as part of dbt-core.

**Comment by benc-db** [comment]
I'm pretty sure we can't do anything about this in the databricks adapter, especially if it is also present in dbt-core.  I recommend you either file a ticket with your Databricks rep or continue the conversation with @Hangzhi.
