### ISSUE TITLE
reopen #500

### ISSUE THREAD

**Issue by leo-schick** [databricks/dbt-databricks#510]
Please reopen #500. It looks like that I can't do this myself.

**Comment by benc-db** [comment]
Do you have a concrete suggestion for how to improve the performance?  If so, we can try to implement it; as I commented on 500 though, using seeds for large table ingest is not an intended use case.

**Comment by leo-schick** [comment]
I guess a upload and a call of `spark.read.option("delimiter", ",").csv(path)` could be a fast option. But would probably require to first upload the file to a temp storage in databricks.

**Comment by leo-schick** [comment]
I found an alternative solution for myself so I do not need anymore a higher csv performance
