### ISSUE TITLE
SSL Certificate verification error

### ISSUE THREAD

**Issue by Lalith-Paluru** [databricks/dbt-databricks#522]
### Describe the bug
dbt-databricks UNABLE TO VERIFY MY SSL CERTIFICATE EVEN THOUGH ITS VALID

### Steps To Reproduce
Hello,
I installed dbt on a virtual python environment and for my application, I need to install elementary plug-in. I have been following the official guidelines provided here For dbt installation: [https://docs.getdbt.com/docs/core/pip-install] and for elementary plugin installation: https://docs.elementary-data.com/tutorial/installing-elementary. Despite of following the guidelines, I'm not able to resolve an error I'm encountering during the runtime while running "dbt run --select elementary".

ERROR:
Runtime Error
  Database Error
    HTTPSConnectionPool(host='adb-915795399904243.3.azuredatabricks.net', port=443): Max retries exceeded with url: /sql/1.0/warehouses/e3796dd6629e1c4a (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)')))

Im using MacOS and my dbt is installed on a python virtual environment.

Please help me resolve this error as it is acting as a huge blocker for my work.

Thanks in advance!

**Comment by benc-db** [comment]
@susodapop do you have any ideas/experience with this?  The error looks to me like the warehouse sent a bad cert.

@Lalith-Paluru if you have a Databricks contact, I recommend filing a ticket with them.  This does not look like a bug I can fix through the adapter.
