### ISSUE TITLE
convert schemaname to lowercase

### ISSUE THREAD

**Issue by bram-83** [databricks/dbt-databricks#523]
### Describe the bug
when we are using mixed case in our schema, dbt doesn't find the schema

### Steps To Reproduce
used mixed / upper casing in the schema name

### Expected behavior
dbt should recognize the schema and apply incremental when applicable.

Via trial and error, I've found that the incremental load only works when the schema's are defined in lowercase. In our CI/CD process, new branches/schema's can have mixed case.

Probably changing the schemaPattern to lowercase would fix the issue.
Listing tables 'catalog : qas, schemaPattern : CH-temp2_prep_md, tableTypes : null, tableName : null'

### System information
**The output of `dbt --version`:**
Running with dbt=1.7.3
Registered adapter: databricks=1.7.2

Thanks in advance,
Regards Bram

**Comment by benc-db** [comment]
Thanks for the report!
