### ISSUE TITLE
unable to connect to Databricks 9.1 LTS

### ISSUE THREAD

**Issue by jmuir99** [databricks/dbt-databricks#53]
Running dbt 1.0.1 with databricks 1.0.1 and spark 1.0.0 plugins.

When running "dbt debug" connection fails giving the following errors

>Runtime Error
 Database Error
   failed to connect

profile.yml contains

projectname:
  outputs:
    dev:
       type: databricks
       schema: curated
       host: https://adb-XXXXXXX.azuredatabricks/net/
       http_path: /sql/protocolv1/o/XXXXXXXXXXXXXXXXXXXXX/XXXXXXXXXXX
       token: dapiXXXXXXXXXXXXXXXXXXXXXXX
  target: dev

Able to connect to databricks via databricks-connect with the same credentials

The following is from the dbt.log

19:00:40.648080 [debug] [MainThread]: Acquiring new databricks connection "debug"
19:00:40.648903 [debug] [MainThread]: Using databricks connection "debug"
19:00:40.649092 [debug] [MainThread]: On debug: select 1 as id
19:00:40.649255 [debug] [MainThread]: Opening a new connection, currently in state init
19:00:52.823291 [debug] [MainThread]: Databricks adapter: Error while running:
select 1 as id
19:00:52.824351 [debug] [MainThread]: Databricks adapter: Database Error
  failed to connect
19:00:52.826960 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f88da4bddc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f88da4d54c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f88da4d5bb0>]}

### Steps To Reproduce
From command line run "dbt debug" within the project directory.  Profile and Project yml files pass.  Then get error message on failure to connect to Azure Databricks.

### Expected behavior
Connection to Azure Databricks

### System information
installed version: 1.0.1
   latest version: 1.0.1

Up to date!

Plugins:
  - databricks: 1.0.1
  - spark: 1.0.0

**The operating system you're using:**
Windows 10 Build 19042.1526 Version 20H2 with WSL 1 running Ubuntu 20.04. 

**The output of `python --version`:**
Python 3.8.10

**Comment by ueshin** [comment]
The `host` configuration seems wrong?
It should be something like `adb-XXXXXXX.azuredatabricks.net` (without `https://` and not `... azuredatabricks/net`)

**Comment by jmuir99** [comment]
that was it.  thanks

**Comment by ueshin** [comment]
Glad to hear the issue was resolved. Thanks!
