### ISSUE TITLE
This Azure storage request is not authorized. 

### ISSUE THREAD

**Issue by rickamsterdam** [databricks/dbt-databricks#534]
### Describe the bug
I'm trying to understand an issue I'm seeing, where when I try to run a model, I receive the following error:

>   This Azure storage request is not authorized. The storage account's 'Firewalls and virtual networks' settings may be blocking access to storage services. Please verify your Azure storage credentials or firewall exception settings.

When I run `dbt debug` everything looks ok and I'm able to connect with the SQL warehouse. I'm authenticating with a PAT, and it's probably a firewall issue from my end, but I don't understand why DBT makes an azure storage request that's being blocked and what traffic I'd need to whitelist. 

### Steps To Reproduce
running `dbt run` with a valid dbt connection in the example project.

### Expected behavior
model runs

### Screenshots and log output
```
dbt debug
13:27:58  Running with dbt=1.7.4
13:27:58  dbt version: 1.7.4
13:27:58  python version: 3.10.10
13:27:58  python path: /Users/a/dev/data/dbt-databricks/dbt-env/bin/python3
13:27:58  os info: macOS-13.4-arm64-arm-64bit
13:27:58  Using profiles dir at /Users/a/.dbt
13:27:58  Using profiles.yml file at /Users/a/.dbt/profiles.yml
13:27:58  Using dbt_project.yml file at /Users/a/dev/data/dbt-databricks/dbt-env/b/dbt_project.yml
13:27:58  adapter type: databricks
13:27:58  adapter version: 1.7.3
13:27:59  Configuration:
13:27:59    profiles.yml file [OK found and valid]
13:27:59    dbt_project.yml file [OK found and valid]
13:27:59  Required dependencies:
13:27:59   - git [OK found]

13:27:59  Connection:
13:27:59    host: adb-XXXXXX.azuredatabricks.net
13:27:59    http_path: /sql/1.0/warehouses/XXXXXX
13:27:59    catalog: XXXX_dev
13:27:59    schema: default
13:27:59  Registered adapter: databricks=1.7.3
13:28:07    Connection test: [OK connection ok]

13:28:07  All checks passed!
```

```
dbt run
13:11:39  Running with dbt=1.7.4
13:11:40  Registered adapter: databricks=1.7.3
13:11:40  Found 2 models, 4 tests, 0 sources, 0 exposures, 0 metrics, 534 macros, 0 groups, 0 semantic models
13:11:40  
13:11:55  Concurrency: 1 threads (target='dev')
13:11:55  
13:11:55  1 of 2 START sql table model default.my_first_dbt_model ........................ [RUN]
13:12:02  1 of 2 ERROR creating sql table model default.my_first_dbt_model ............... [ERROR in 6.78s]
13:12:02  2 of 2 SKIP relation default.my_second_dbt_model ............................... [SKIP]
13:12:02  
13:12:02  Finished running 1 table model, 1 view model in 0 hours 0 minutes and 22.10 seconds (22.10s).
13:12:02  
13:12:02  Completed with 1 error and 0 warnings:
13:12:02  
13:12:02    Runtime Error in model my_first_dbt_model (models/example/my_first_dbt_model.sql)
  This Azure storage request is not authorized. The storage account's 'Firewalls and virtual networks' settings may be blocking access to storage services. Please verify your Azure storage credentials or firewall exception settings.
13:12:02  
13:12:02  Done. PASS=0 WARN=0 ERROR=1 SKIP=1 TOTAL=2
```

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.7.4
  - latest:    1.7.4 - Up to date!

Plugins:
  - databricks: 1.7.3 - Up to date!
  - spark:      1.7.1 - Up to date!
```

**The operating system you're using:**
Mac
**The output of `python --version`:**
```
Python 3.10.10
```

**Comment by benc-db** [comment]
You're hitting this with the example project?  I've never seen that before; usually these sorts of errors crop up if you're using external locations / location_root.  If you have a Databricks contact, please work with them to debug or file a ticket so that we can get more information about your particular setup.

**Comment by rickamsterdam** [comment]
> You're hitting this with the example project?

correct, seeing this with the example project generated by `dbt init`. I'll see if we can forward this ticket to our AM, thanks for looking into it!

**Comment by rickamsterdam** [comment]
I was using a serverless sql warehouse which was prohibited by my organisation 👍
