### ISSUE TITLE
Materialized views & streaming tables don't support redefinition without dropping the full table

### ISSUE THREAD

**Issue by lennartkats-db** [databricks/dbt-databricks#561]
# Issue

This is a tracking ticket for a platform limitation currently described in https://docs.getdbt.com/reference/resource-configs/databricks-configs#limitations:

> [If] you change the model definition of your materialized view or streaming table, you will need to drop the materialization in your warehouse directly before running dbt again; otherwise, you will get a refresh error.

(By creating a tracking ticket for this we have something that we can point customers to, so they can track progress of this work.)

# Workaround

As a workaround, you can either manually drop the target table, or you can use dbt with the `--full-refresh` option. As an example, the following does a full refresh of the `orders` model:

```
$ dbt run --full-refresh --model orders
```

**Comment by benc-db** [comment]
Working on this now.

**Comment by benc-db** [comment]
This should now be solved with 1.8.0b1
