### ISSUE TITLE
When using the Incremental Append Strategy, the newly added columns in SQL are not being added.

### ISSUE THREAD

**Issue by case-k-git** [databricks/dbt-databricks#567]
### Describe the feature

Currently, If a new column is added to an existing SQL model, the newly added column will not be added, and data will only be added to the old columns that exist in the existing table. Since no error occurs, data will not be added despite the addition of columns to the SQL model, and subsequent dbt with dependencies will fail due to the lack of columns.

### Describe alternatives you've considered
Add the validation if  new column is missing into existing table

### Additional context
Please include any other relevant context here.

### Who will this benefit?
What kind of use case will this feature be useful for? Please be specific and provide examples, this will help us prioritize properly.

We will be able to know that  new column is missing . Currently Insert into existing table without error and new columns data is not add it 

### Are you interested in contributing this feature?
Let us know if you want to write some code, and how we can help.

Yes

**Comment by benc-db** [comment]
The default strategy is ignore.  Have you tried on_schema_change='fail'?

**Comment by case-k-git** [comment]
Thank you I confirmed let me close this PR
