### ISSUE TITLE
Respect profile schema when creating `__dbt_tmp` views

### ISSUE THREAD

**Issue by rlh1994** [databricks/dbt-databricks#574]
### Describe the feature
Currently the `__dbt_tmp` views  are created directly in the default schema for the connection (which is often `default`) rather than in the schema specified in the profile. This creates issues for users with heavily locked down permissions as they may not have the permissions to write, or in the case I have experience, read from this schema. These views should be created in the schema specified by the profile to ensure access is as expected.

### Describe alternatives you've considered
Getting the user access to the default schema, or having the default schema changed within the workspace, neither of which are ideal.

### Additional context
Logs of a run where a temp view is created, note that the main table itself is correctly prefixed with the catalog and schema:
```
...
[0m10:14:22.673975 [debug] [Thread-1  ]: On model.snowplow_unified.snowplow_unified_sessions: /* {"app": "dbt", "dbt_version": "1.7.2", "dbt_databricks_version": "1.7.1", "databricks_sql_connector_version": "2.9.3", "profile_name": "default", "target_name": "databricks", "node_id": "model.snowplow_unified.snowplow_unified_sessions"} */

      describe extended `hive_metastore`.`dbt_ryan_derived`.`snowplow_unified_sessions`
  
[0m10:14:22.889692 [debug] [Thread-1  ]: SQL status: OK in 0.2199999988079071 seconds
[0m10:14:22.893677 [debug] [Thread-1  ]: Using databricks connection "model.snowplow_unified.snowplow_unified_sessions"
[0m10:14:22.894236 [debug] [Thread-1  ]: On model.snowplow_unified.snowplow_unified_sessions: /* {"app": "dbt", "dbt_version": "1.7.2", "dbt_databricks_version": "1.7.1", "databricks_sql_connector_version": "2.9.3", "profile_name": "default", "target_name": "databricks", "node_id": "model.snowplow_unified.snowplow_unified_sessions"} */

  
    create or replace temporary view `snowplow_unified_sessions__dbt_tmp` as
      




select *
  , DATE(start_tstamp) as start_tstamp_date
from `hive_metastore`.`dbt_ryan_scratch`.`snowplow_unified_sessions_this_run`
where cast(True as boolean) --returns false if run doesn't contain new events.
  
[0m10:14:23.109612 [debug] [Thread-1  ]: SQL status: OK in 0.20999999344348907 seconds
[0m10:14:23.134403 [debug] [Thread-1  ]: Using databricks connection "model.snowplow_unified.snowplow_unified_sessions"
[0m10:14:23.135018 [debug] [Thread-1  ]: On model.snowplow_unified.snowplow_unified_sessions: /* {"app": "dbt", "dbt_version": "1.7.2", "dbt_databricks_version": "1.7.1", "databricks_sql_connector_version": "2.9.3", "profile_name": "default", "target_name": "databricks", "node_id": "model.snowplow_unified.snowplow_unified_sessions"} */

      describe extended `snowplow_unified_sessions__dbt_tmp`
  
[0m10:14:23.289936 [debug] [Thread-1  ]: SQL status: OK in 0.15000000596046448 seconds
[0m10:14:23.298023 [debug] [Thread-1  ]: Using databricks connection "model.snowplow_unified.snowplow_unified_sessions"
[0m10:14:23.299201 [debug] [Thread-1  ]: On model.snowplow_unified.snowplow_unified_sessions: /* {"app": "dbt", "dbt_version": "1.7.2", "dbt_databricks_version": "1.7.1", "databricks_sql_connector_version": "2.9.3", "profile_name": "default", "target_name": "databricks", "node_id": "model.snowplow_unified.snowplow_unified_sessions"} */

      describe extended `hive_metastore`.`dbt_ryan_derived`.`snowplow_unified_sessions`
  
[0m10:14:23.510824 [debug] [Thread-1  ]: SQL status: OK in 0.20999999344348907 seconds
...
```

Comparing to running the same in Snowflake, they provide full path for the temp view. 

### Who will this benefit?
Users with strict locked down permissions only having access to their schema.

### Are you interested in contributing this feature?
No, but I believe it's just this line here that needs to be changed to create the relation with the schema and database rather than just the identifier https://github.com/databricks/dbt-databricks/blob/d54453e0e93ec8c8f882df0a60476ee8b5b67383/dbt/include/databricks/macros/adapters/relation.sql#L10

**Comment by benc-db** [comment]
Thanks for the report, and if it is as simple as the one line change, I'll try to get the fix in the next release after we fix the current warehouse connection issue.

**Comment by rlh1994** [comment]
Actually turns out this is not possible in databricks, which is probably why it was done this way in the first place, so am closing.

`[TEMP_VIEW_NAME_TOO_MANY_NAME_PARTS] CREATE TEMPORARY VIEW or the corresponding Dataset APIs only accept single-part view names, but got: `

**Comment by benc-db** [comment]
@rlh1994 I'm pretty sure you're right, and because it's been about 6 months since I last looked into that issue, I had just forgotten.
