### ISSUE TITLE
Migrate to using decoupled new decoupled core/adapters architecture 

### ISSUE THREAD

**Issue by colin-rogers-dbt** [databricks/dbt-databricks#585]
### Describe the feature
Opening this issue to track dbt-databricks [decoupling migration](https://github.com/dbt-labs/dbt-adapters/discussions/87) and provide additional guidance/context. 

Specific recommendations:
* In the feature branch update https://github.com/databricks/dbt-databricks/blob/main/dev-requirements.txt#L27 to install `dbt-core` and `dbt-spark` from the main branch of their respective repos instead of installing from pypi. 
* Review the [dbt-spark migration PR](https://github.com/dbt-labs/dbt-spark/pull/972/files), functional changes are minor but potentially subtle. One example is [this change](https://github.com/dbt-labs/dbt-spark/pull/972/files#diff-57462633056600a2c01a6052275c92848fbd6a524f87567a5207db997453f1cfL484) swapping out `DbtProfileError` for `DbtConfigError`

### Describe alternatives you've considered
Not doing this will block dbt-databricks from working with post 1.8 dbt-core versions. 

### Additional context
N/A

### Who will this benefit?
All dbt-databricks users and maintainers!

### Are you interested in contributing this feature?
Happy to help out however we can.

**Comment by benc-db** [comment]
Ack, thanks for filing
