### ISSUE TITLE
Snapshot Jobs randomly erroring due to parallel run of completely separate snapshots

### ISSUE THREAD

**Issue by crystalro0** [databricks/dbt-databricks#598]
### Describe the bug
While running multiple snapshot jobs in parallel, there are random `Unexpected relation type discovered` errors. It seems as if the `_tmp` tables built are dropped while the metadata was being fetched.

### Steps To Reproduce
1. Have multiple snapshot jobs that run in parallel but do not have any overlaps in the DAG.
2. Look for created __tmp tables that get dropped at the end of the snapshot run.
3. Based on the logs, it appears the error message comes from the 'describe tables in schema' command which returns an error for completely unrelated '__tmp' tables that no longer exist because they were deleted during a snapshot proecess from a different job.
4. The error message causes the job to fail, even though it is irrelevant for the running snapshot.

### Expected behavior
Catalog updated with the appropriate metadata

### Screenshots and log output
```
2024-02-26 05:47:41.054475 (ThreadPoolExecutor-1_0): 05:47:41  Databricks adapter: Error while running:
macro list_relations_without_caching
2024-02-26 05:47:41.055218 (ThreadPoolExecutor-1_0): 05:47:41  Databricks adapter: Runtime Error
  Unexpected relation type discovered: Database:test_db, Relation:test_historical_snapshot__dbt_tmp
2024-02-26 05:47:41.056008 (ThreadPoolExecutor-1_0): 05:47:41  Databricks adapter: Error while retrieving information about `test_db`.`test_historical_stg`: Runtime Error
  Unexpected relation type discovered: Database:test_db, Relation:test_historical_snapshot__dbt_tmp
```

### System information

**The output of `dbt --version`:** 1.7.8
**dbt-databricks:** 1.7.7

**Comment by benc-db** [comment]
@crystalro0 can you file a ticket with your Databricks contact so that I can get the full dbt.log?  Or you can email it to me if you prefer: ben.cassell@databricks.com.
