### ISSUE TITLE
Bug: Delta Clones unsupported by `DatabricksRelationType`

### ISSUE THREAD

**Issue by ShaneMazur** [databricks/dbt-databricks#601]
### Describe the bug

Sources do not have support for [Databricks clones](https://docs.databricks.com/en/sql/language-manual/delta-clone.html) in [DatabricksRelationType](https://github.com/databricks/dbt-databricks/blob/1d21b328fd2ca57cabe0b8bd2dd09fdbcc884a3b/dbt/adapters/databricks/relation.py#L31-L37)

### Steps To Reproduce

I've encountered this issue in a few places but most recently using the [dbt-labs/dbt-codegen](https://github.com/dbt-labs/dbt-codegen) package. Specifically:
```sh
dbt run-operation generate_source --args '{
        "schema_name": "my_schema",
        "database_name": "my_source"
    }'
```

### Expected behavior

Should return correct source definition yaml

### Screenshots and log output

![Screenshot 2024-03-01 at 4 48 14 PM](https://github.com/databricks/dbt-databricks/assets/30323745/63eee208-dc07-43a5-9add-1120dbcc8871)

**Comment by benc-db** [comment]
Interesting.  Do you have a dbt.log that can provide the stack so I know where the exception is raised?

**Comment by benc-db** [comment]
Can you try 1.7.9 and let me know if you still have this issue?  I removed one place that raises an exception, but uncertain if its the same issue you're hitting.
