### ISSUE TITLE
Feature request: Support for Delta Lake 'CHANGE DATA FEED' in Incremental Models within dbt Databricks Adapter

### ISSUE THREAD

**Issue by hwspuijbroek** [databricks/dbt-databricks#630]
### Describe the feature
I propose enhancing the dbt Databricks adapter to support incremental models utilizing Databricks' Delta Lake CHANGE DATA FEED feature, specifically by enabling the configuration option delta.enableChangeDataFeed=true and integrating the table_changes function within dbt's incremental strategy (merge process). This integration should facilitate more efficient and robust data transformation pipelines, especially in multi-layered data architectures like bronze-to-silver and silver-to-gold processes. The goal is to leverage Delta Lake's ability to track changes at a row level, thereby enabling more granular and efficient data processing in dbt.

### Describe alternatives you've considered
Currently, the most common approach for handling incremental data transformations in dbt involves filtering data based on a specific timestamp or date column. This method, while effective in certain scenarios, can be less efficient or reliable, particularly in cases where the timestamp data may not accurately capture all necessary changes, or in complex data architectures where changes need to be tracked across multiple layers or tables.

Another alternative could be manually implementing logic to simulate the CHANGE DATA FEED feature within dbt models, but this approach would likely be cumbersome, error-prone, and not as performant as a native integration.

### Additional context
The motivation for this feature request is inspired by the capabilities demonstrated in the Databricks SQL context, as outlined in the article ["Incremental, Parameterized, and Dynamic SQL all on Databricks SQL"](https://medium.com/dbsql-sme-engineering/incremental-parameterized-and-dynamic-sql-all-on-databricks-sql-5271ebb87bdb). The article showcases the power of Delta Lake's CHANGE DATA FEED and the table_changes function in tracking and processing data changes efficiently. A native integration of these features within dbt's Databricks adapter would significantly enhance the tool's capabilities for handling incremental data transformations in a more granular and efficient manner.

### Who will this benefit?
This feature would benefit data engineers and data architects who utilize dbt in conjunction with Databricks for complex data transformation and ETL pipelines, particularly in environments where data is organized into multi-tiered storage layers (e.g., bronze, silver, gold). Examples include:

Data teams managing large and rapidly changing datasets, where efficient incremental processing can lead to significant performance gains and cost savings.
Organizations implementing complex data governance and lineage tracking requirements, where the ability to capture and process granular changes at the row level can enhance data auditability and quality.
Teams migrating from traditional ETL tools to modern data stack technologies, seeking to leverage advanced features of Databricks Delta Lake within dbt workflows.
Implementing this feature would align dbt more closely with the advanced capabilities of Databricks, thereby enhancing its value proposition for data teams working in dynamic and data-intensive environments.

**Comment by benc-db** [comment]
I don't think you need any changes in the adapter to facilitate this.  You can set tblproperties on your bronze tables to turn on CDC, and then in your is_incremental block, look for max _commit_version.  What is missing?

**Comment by hwspuijbroek** [comment]
Hi @benc-db you are correct. But you really need to known how to work with variables for retreiving the correct (latest) commit version for example. It is not that it works based on specific parameters. I didn't see a lot off information about this feature and how you should implement this in DBT (with variables for example). So Maybe it is a lack off my knowledge about this feature and dbt implementation.

**Comment by benc-db** [comment]
err, the changeDataFeed should be set on the source table, not this one, I think.

**Comment by hwspuijbroek** [comment]
Thanks!

**Comment by mi-volodin** [comment]
@hwspuijbroek no, only on source. You have to store commit version in the target table (and can use different name for it). Or use some other meta-information like `current_timestamp()` stored in the source table. But mind that logic of CDF extraction will change. And also that in CDF stores not the statement start time, but commit time.

**Comment by ewang-loyalty** [comment]
@benc-db Is it possible to use `table_changes` function in dbt instead of `is_incremental` macro to extract incremental records?

**Comment by ewang-loyalty** [comment]
@mi-volodin Ah sorry let me give a bit more context - I'm looking into the possibility of processing incremental rows from an output table generated from a delta live table pipeline using dbt. This upstream table could either be a streaming table or I would need to use `table_changes` function to extract out incremental rows. What's the proper dbt way of achieving this?

**Comment by nthapa14** [comment]
@mi-volodin Could you provide an example on how to use `table_changes` within `is_incremental` block?

**Comment by mi-volodin** [comment]
@ewang-loyalty there are actually multiple ways to implement this. The trickiest thing is probably the part of identification of the increment.

The logic of the model will follow more or less the following design:

1. **Identify the state of a target table**. 
    - If it doesn't exist (may be checked by `is_incremental == False`) do "fresh run" logic. Might be full load, might be a limited one - depends on your specific use case.
    - If it exists (in that case `is_incremental == True`) identify the latest **state** that is usually tracked by an explicit attribute with a certain `timestamp` (more on this below).
2. Depending on the case above - select from the source table, filtering records if required.
3. Merge or append them to the target table (also depends on your logic).

In a SQL form it will look alike this one

```sql

{% if is_incremental %}
   [ part that resolves target state timestamp ]
select
    [attr list],
    [state_timestamp] as tech_change_ts /* the attribute name is for example */ 
from
    ...
where
   [filtering state logic]
{% else %}
select
    [attr_list],
    [DEFAULT_timestamp] as tech_change_ts
from
    ...
where
    [filtering for initial run]
{% endif %}
```

Now, there are several ways to identify the changes and that will affect the timestamp that you have to track:

1. **Change data feed**. In that case if you select using `table_changes` function you will get not just "new records", but all the changes. Deletions and updates are tracked as well, and updates will have 2 records: pre and post image.
  The advantage of this is that you see all the changes that happen. But there are a lot of disadvantages (challenges):
    - You will receive the `_commit_timestamp` as a state timestamp, for incremental runs you will have to pick the changes for `max(tech_change_ts)` in the target + `1us`. The `DEFAULT_timestamp` should be also obtained from change feed, and cannot be generated.
    - You will have to aggregate the changes using the table primary key, to ensure that in case of multiple changes you will ingest only efficient state.
    - As far as I remember, `table_changes` won't allow you to pass a dynamically resolved argument. Which means that you will have to resolve the timestamp from which you need to filter on a macro level, or probably in 15+ runtimes the SQL parameters may be used (I don't know, never tried).
    - Table changes "memory" is limited to the time travel capability. When you vacuum and clean the old states of table - the changes are also lost.

2. **[Row tracking](https://docs.databricks.com/en/delta/row-tracking.html)**. That mechanism is introduced relatively recently to enable lineage feature in the Unity catalog. So if you use one, probably it is enabled by default. This approach differs from CDF in a sense that it doesn't track deletions or updates as separate records, but you will see the commit timestamp for each row, and will be able to just filter new records dynamically with a filter `_metadata.row_commit_version > X`, where `X` is a version that you can resolve from `Describe table history` (works in CTE).
  From my perspective - this approach is slightly better if you don't have to track deletions or updates. Which is a very common case for distributed systems data architecture.

3. **Explicit state tracking**. If you control the upstream table and you can ingest there an attribute that will just fill `current_timestamp()` into some attribute - you can use this as well for tracking. This is very similar to a previous one. The difference is:
    - The `current_Timestamp()` resolves to the timestamp when query execution starts. Do not mix it with commit timestamp, they are different.
    - It does not rely on Delta capabilities and will work in almost any processing engine.
    - The SQL for filtering becomes simpler as you have to operate with `max(tech_change_ts)` from target table and just filter by it on source.


I hope that helps to select the approach. My personal preference is to stay away from CDF if you don't have to identify deletions and updates. And if you do - write a common macro that will wrap that bulky logic of increment extraction.

**Comment by mi-volodin** [comment]
@nthapa14 hope the post above helps. The biggest pain point from my perspective - is extracting the target state, adding `1us` and storing it as a string in a variable. I cannot provide that code for you and I unfortunately don't have time to experiment with it now.

If you I can clarify anything else for you - please ask.
