### ISSUE TITLE
Authentication Issue: Polling Python Job Status - Access Token Cached on Creation

### ISSUE THREAD

**Issue by sf-git** [databricks/dbt-databricks#647]
This code creates and caches the m2m_auth token. If the Python job runs longer than the token's time-to-live (usually one hour), the polling job status code that uses that token will fail with 403.  

In some cases, 403 returns an XML payload, and a proper auth exception is ignored. Instead, the adapter throws an "invalid JSON payload" exception.

Fails here:
https://github.com/databricks/dbt-databricks/blob/a33829e5b970b748135d92353637461389241053/dbt/adapters/databricks/python_submissions.py#L189

Due to:
https://github.com/databricks/dbt-databricks/blob/a33829e5b970b748135d92353637461389241053/dbt/adapters/databricks/python_submissions.py#L466

**Comment by benc-db** [comment]
I might have fixed this in the PR I'm about to put out.  I saw that in the BearerAuth class it was invoking the function at create, rather than on __call__
