### ISSUE TITLE
Multiple sql statements in a prehook string fails to parse

### ISSUE THREAD

**Issue by Oremite** [databricks/dbt-databricks#66]
### Describe the bug
Having multiple sql statements in a dbt prehook fails.

### Steps To Reproduce
Run an example model such as:
```
{{
  config(
    pre_hook="select 'a';
              select 'b'; "
  )
}}

select * from some_schema.some_table
```
using `dbt run` and get the error:
```
Runtime Error in model atty (models/simple_demo/atty.sql)
16:58:51    Query execution failed.
16:58:51    Error message: org.apache.spark.sql.catalyst.parser.ParseException: 
16:58:51    extraneous input 'select' expecting {<EOF>, ';'}(line 4, pos 14)
16:58:51    
16:58:51    == SQL ==
16:58:51    /* {"app": "dbt", "dbt_version": "1.0.3", "profile_name": "tdss_dbt_test", "target_name": "dev", "node_id": "model.tdss_dbt_test.atty"} */
16:58:51    
16:58:51            select 'a';
16:58:51                  select 'b'
16:58:51    --------------^^^
```

### Expected behavior
If you run the same prehook sql (`select 'a'; select 'b';`) directly in a Databricks notebook against the same cluster, it will execute successfully.
Furthermore, multiple sql statements in a prehook are supported in the dbt documentation https://docs.getdbt.com/reference/resource-configs/pre-hook-post-hook

### System information
**The output of `dbt --version`:**
```
dbt --version
installed version: 1.0.3
   latest version: 1.0.4

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - databricks: 1.0.1 - Up to date!
  - spark: 1.0.0 - Up to date!

```

**The operating system you're using:**
MacOS 12.2.1 (Monterey)

**The output of `python --version`:**
Python 3.8.12

### Additional context
The cluster I am connected to uses DBR 9.1.
I have not tried this with post hooks yet, but I assume it will have the same behavior.
My particular instance is using a PVC release.

**Comment by superdupershant** [comment]
Hi @Oremite the syntax for multiple queries in a dbt prehook is defined [here](https://docs.getdbt.com/reference/resource-configs/pre-hook-post-hook). They need to be a an array of strings.

```
{{
  config(
    pre_hook= ["select 'a'", "select 'b'"]
  )
}}
```

**Comment by Oremite** [comment]
Ahhh... you're right.  That documentation syntax is never clear to me.  Thank you, @superdupershant !
