### ISSUE TITLE
dbt snapshot doesn't work for a query

### ISSUE THREAD

**Issue by AjayChauhan-2022** [databricks/dbt-databricks#68]
### Describe the bug
when you define dbt snapshot using query. it produces the error as "Create or Replace Table  DB_name.snapshot_name" at Table section. Please find attached screenshot for it.

### Steps To Reproduce
Define any simple snapshot using query.
then execute command : dbt snapshot --select SNAPSHOT_NAME

### Expected behavior
we expect that SNAPSHOT should have been created in DBKS Delta table

### Screenshots and log output
![image](https://user-images.githubusercontent.com/102654291/160855246-9059dd1a-59f8-47b8-b7d5-c23b307be65d.png)

![image](https://user-images.githubusercontent.com/102654291/160855377-cd46a788-5201-4aba-9e60-f6cddefe8534.png)

### System information
**The output of `dbt --version`:**
dbt version 1..0.4

dbt-databricks 1.0.1

<output goes here>
```

**The operating system you're using:**
Windows

**The output of `python --version`:**
Python 3.9.11

### Additional context
Add any other context about the problem here.

**Comment by allisonwang-db** [comment]
Hi @AjayChauhan-2022, thanks for reporting the issue. What Databricks Runtime version are you using?

**Comment by allisonwang-db** [comment]
DBR 6.4 is not supported. See https://github.com/databricks/dbt-databricks#compatibility. The query should work with DBR 7.3 and above versions.

**Comment by AjayChauhan-2022** [comment]
Thanks Allison for quick response.
I confirm that it works with DBR 10.3 as expected.

![image](https://user-images.githubusercontent.com/102654291/161181213-0441c385-5137-4dfa-9946-340ffa74d492.png)
