### ISSUE TITLE
Suggestions for running DBT unit tests in an isolated fashion

### ISSUE THREAD

**Issue by ajsquared** [databricks/dbt-databricks#685]
My team is excited to try out the new [unit testing](https://docs.getdbt.com/docs/build/unit-tests) functionality in DBT 1.8.0. However, this does still require connecting to Databricks to run the unit tests.

We'd like to run the DBT unit tests in CI, but prefer to keep CI isolated from external services.

Do you have any suggestions for a good way to still run the DBT unit tests without actually connecting to Databricks?

I was considering using a sqlite target, but that wouldn't work for any models that use Spark/Databricks SQL specific features.

**Comment by benc-db** [comment]
@ajsquared at this point, I would ask in the dbt slack.  I haven't had a chance yet to start using the unit test framework personally, so I don't have any particular recommendations.
