### ISSUE TITLE
Regression in insert_overwrite incremental strategy

### ISSUE THREAD

**Issue by ajsquared** [databricks/dbt-databricks#687]
### Describe the bug
After upgrading to `dbt-databricks` 1.8.0, incremental models using the `insert_overwrite` strategy replace the entire table rather than adding/overwriting specific partitions.

### Steps To Reproduce
We upgraded yesterday to `dbt-core` and `dbt-databricks` 1.8.0. We had several incremental models using the `insert_overwrite` strategy, with config like

```
{{ config(
  partition_by=['date_partition'],
  materialized='incremental',
  incremental_strategy = 'insert_overwrite'
) }}
```

Before the upgrade these incremental models were running normally; each incremental run would add a new partition and preserve all historical partitions.

On the next runs after the upgrade, we observed the historical data was lost. For instance, if an incremental job produced `date_partition=2024-05-28`, only that partition would be present in the table. We could recreate the historical data by running the model with `--full-refresh`, but the next incremental run would again remove all the historical data.

I believe this is due to removing `set spark.sql.sources.partitionOverwriteMode = DYNAMIC` in #623. When we added this setting to our Databricks cluster, the previous behavior was restored.

I know that property isn't supported in SQL warehouses, but this is a significant regression in the behavior of this adapter.

### Expected behavior
When an incremental model runs with the `insert_overwrite` strategy, only specific partitions should be added/overwritten, not the entire table. This should be the default behavior and not require custom configuration to support.

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.8.0
  - latest:    1.8.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - databricks: 1.8.0 - Up to date!
  - spark:      1.8.0 - Up to date!
```

**The operating system you're using:**
Clients are using OS X, the DBT models are running on a Databricks cluster with DBR 14.3

**The output of `python --version`:**
```
Python 3.11.7
```

**Comment by benc-db** [comment]
Agreed.  Reasoning at the time was that spark settings should not be managed by dbt-databricks, but I think the pain of this regression is great enough to undo it.

**Comment by benc-db** [comment]
Also, apologies that we didn't document this change.
