### ISSUE TITLE
Support for partition overwrite with Delta

### ISSUE THREAD

**Issue by dejan** [databricks/dbt-databricks#75]
### Describe the feature

_This was reported in https://github.com/dbt-labs/dbt-spark/issues/155 but I think you might be more interested in resolving the issue_ 

> Currently, the insert_overwrite strategy throws an error if file format is set to delta because it doesn't support dynamic partition overwrite

[Delta already supports partitions overwrite](https://docs.databricks.com/spark/latest/spark-sql/language-manual/sql-ref-syntax-dml-insert-into.html) but it seems that dbt adapter implementation is not making use of it.

### Describe alternatives you've considered

I could not find a way to atomically overwrite a partition.

### Who will this benefit?

Everyone using dbt and Delta.

**Comment by bilalaslamseattle** [comment]
@dejan a quick update on this. The Delta folks at Databricks are looking at this for the roadmap. It's prioritized, I'll post back here once it's released.

**Comment by creativedutchmen** [comment]
Any updates on this?

**Comment by bilalaslamseattle** [comment]
@creativedutchmen this capability it is in Delta Lake 2.0. We now have to implement it in dbt-databricks. It's on our radar. @superdupershant @ueshin and @allisonwang-db FYI.

**Comment by letianw91** [comment]
+1 on this. Adding one data point that this will be a blocker for us for adapting dbt

**Comment by creativedutchmen** [comment]
Great, thanks! This will greatly reduce the runtime of some of our heaviest models :)

**Comment by flvndh** [comment]
I submitted a PR to include it in `dbt-spark` if you want to look at it: https://github.com/dbt-labs/dbt-spark/pull/430

**Comment by creativedutchmen** [comment]
Still relevant for me

**Comment by dejan** [comment]
@bilalaslamseattle please share some updates on this.

**Comment by andrefurlan-db** [comment]
This issue has been address by #310

**Comment by dejan** [comment]
I don't think it was a good decision to close this because #310 has a major flaw which was not resolved (only documented) https://github.com/databricks/dbt-databricks/issues/334

**Comment by dejan** [comment]
I haven't confirmed this but by looking at the [documentation](https://docs.getdbt.com/reference/resource-configs/databricks-configs#the-insert_overwrite-strategy) insert_overwrite apparently now supports dynamic partition overwrite (it no longer errors for Delta), however it stated that it only works for All-purpose clusters which is also a major drawback as that's not cost-efficient.

Can someone please confirm the status quo and plans on properly providing such a basic and common case such as partition overwrite?

**Comment by bilalaslamseattle** [comment]
> however it is stated that it only works for All-purpose clusters which is also a major drawback as that's not cost-efficient.
@andrefurlan-db can you confirm if this is correct? Seems odd.

**Comment by benwhelankf** [comment]
@bilalaslamseattle / @andrefurlan-db was there an update on this one or a thread somewhere else? When I run partition overwrite against SQL warehouses,  I get:

`  Error running query: [_LEGACY_ERROR_TEMP_DBR_0222] org.apache.spark.sql.catalyst.ExtendedAnalysisException: Configuration spark.sql.sources.partitionOverwriteMode is not available.`

Looks like its attempting to set some custom spark config which I don't think is allowed on SQL warehouses.

**Comment by SemyonSinchenko** [comment]
Are there any plans to implement it? Or any updates?
