### ISSUE TITLE
spark_optimize_delta_tables does not work on databricks

### ISSUE THREAD

**Issue by stegus64** [databricks/dbt-databricks#770]
dbt run-operation spark_optimize_delta_tables
06:24:27 Running with dbt=1.8.5
06:24:28 Registered adapter: databricks=1.8.5
06:24:29 Found 235 models, 17 snapshots, 83 data tests, 6 seeds, 142 sources, 5 exposures, 785 macros
06:24:30 Encountered an error while running operation: Runtime Error
Runtime Error
[PARSE_SYNTAX_ERROR] Syntax error at or near '''': missing 'LIKE'. SQLSTATE: 42601 (line 2, pos 29)
== SQL ==
/ {"app": "dbt", "dbt_version": "1.8.5", "dbt_databricks_version": "1.8.5", "databricks_sql_connector_version": "3.1.2", "profile_name": "liseberg-databricks", "target_name": "dev", "connection_name": "macro_spark_optimize_delta_tables"} /
show table extended in like ''
-----------------------------^^^

I have created an issue here: https://github.com/dbt-labs/spark-utils/issues/38
But since I do not know where the real problem is I create an issue in this repo as well.

>dbt --version 
Core:
  - installed: 1.8.5
  - latest:    1.8.5 - Up to date!

Plugins:
  - databricks: 1.8.5 - Up to date!
  - spark:      1.8.0 - Up to date!

>python --version
Python 3.11.6

packages.yml
--------------
packages:
  - package: dbt-labs/dbt_utils
    version: 1.2.0
  - package: dbt-labs/dbt_external_tables
    version: 0.9.0    
  - package: dbt-labs/spark_utils
    version: 0.3.0

**Comment by benc-db** [comment]
Since we have no code for that operation, I suspect the fix would have to come from them.

**Comment by stegus64** [comment]
This problem is caused by a change in dbt-spark. https://github.com/dbt-labs/dbt-spark/issues/1048
It should be fixed there.
Closing this issue.
