### ISSUE TITLE
Set unique table suffix to allow parallel incremental execution

### ISSUE THREAD

**Issue by huangxingyi-git** [databricks/dbt-databricks#810]
### Describe the feature
For some specific cases (eg. backfill very large amount of data), we need to execute parallel multiple `dbt run` of specific incremental(`replace_where`) model in which we pass the date (or country) as var argument.
For example, we have a model we run every day using Airflow for which we pass the a date relative to the Airflow scheduler.
FYI
https://github.com/dbt-labs/dbt-athena/pull/650/files

If we want to process by batch of N days in parallel using Airflow concurrency, we need the tmp table create by each of the dbt run to be unique. Else, you are going to end up with N insert attempting to run with the same __dbt_tmp name, creating conflict and ultimately creating failure.

### Who will this benefit?
For those who uses `repalce_where` as incremental strategy.
Example Use Case: Run the same incremental model concurrently with different `--vars` in order to parallelly insert multiple data partitions

### Are you interested in contributing this feature?
I am interested in contributing to this feature if needed.

**Comment by huangxingyi-git** [comment]
How can I create PR?
i tried to push my feature branch to github and met below error
``` 
% git push origin unique-temp-table-name:huangxingyi/unique-temp-table-name

remote: Permission to databricks/dbt-databricks.git denied to huangxingyi-git.
fatal: unable to access 'https://github.com/databricks/dbt-databricks.git/': The requested URL returned error: 403```

**Comment by benc-db** [comment]
This issue is going to solved more comprehensively with https://github.com/dbt-labs/dbt-core/discussions/10672; however, I'll take a look at your PR, and assuming it doesn't hurt any other use case, I'm not against taking this in the short term.
