### ISSUE TITLE
I'm not able to run code developed using dbt directly in Databricks.

### ISSUE THREAD

**Issue by ac-garcia** [databricks/dbt-databricks#83]
### Describe the bug
I'm not able to run code developed using dbt directly in Databricks.

I'm trying to configure a CI/CD process using Databricks jobs to automatically run the SQL codes. We usually do this using Airflow and this is the first time we are configuring it directly in Databricks. However, when trying to connect, DBT (or Python, I don't know) gives an error that it doesn't have the logs function.

### Steps To Reproduce

1) Create a venv with Python 3.8.10
`py -m venv venv`
`source venv/Scripts/activate`

*In this case, I'm on Windows 10, but I don't think it will impact the next steps for reprodute.*

2) Install and upgrade dbt-databricks

`pip install dbt-databricks`
`pip install --upgrade dbt-databricks`

![image](https://user-images.githubusercontent.com/50485543/163908909-4a63f82c-3271-4a7b-8d96-26810e38198a.png)

3) Generate a dummy project

`dbt init jaffle_shop`

4) Check if connection is working

`dbt debug`
![image](https://user-images.githubusercontent.com/50485543/163909115-eb1d582e-38de-4384-bab4-70faf4cbdd99.png)

5) Commit all changes in a repository test

6) Add repository in Repos Databricks and give a pull refresh

7) Create a notebook in same diretory for test

8) Install requirements and debug dbt
*In this case, we have only dbt-databricks to install*

`%pip install dbt-databricks`
`%sh
dbt --version`
![image](https://user-images.githubusercontent.com/50485543/163910099-d741120b-8d1d-4079-9015-2d9815f45112.png)

`%sh
dbt debug`

![image](https://user-images.githubusercontent.com/50485543/163910237-bda1711e-5a58-4c80-b099-2387f6e1f6c1.png)

### Expected behavior
The expected result of dbt debug is the connection indicator working.
Like this:
![image](https://user-images.githubusercontent.com/50485543/163910401-7c705b9f-4afd-4831-9576-20a3d8783eb4.png)

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**The output of `dbt --version`:**
![image](https://user-images.githubusercontent.com/50485543/163910507-7a886f62-2b43-4b8e-b9ea-55249fbf6872.png)

### Additional context
We tried to install another version of dbt-databricks, but every time we try, the installed version always comes 1.0.4, as if it didn't obey the command directed.

As happen in this case:
![image](https://user-images.githubusercontent.com/50485543/163910879-25f8c7d1-e7c5-4627-9ea9-bdbd469e8a76.png)

**Comment by bilalaslamseattle** [comment]
@ac-garcia thanks for opening the issue. If you are trying to run a dbt project as a job, we are actually previewing this capability right now. Would you be interested in trying it out? Then there's no need to run a notebook.

**Comment by ac-garcia** [comment]
> @ac-garcia thanks for opening the issue. If you are trying to run a dbt project as a job, we are actually previewing this capability right now. Would you be interested in trying it out? Then there's no need to run a notebook.

Hi @bilalaslamseattle ! Thanks for the answer. I'm interested in testing it. Just help me with the steps I should follow to do this experiment, please.

**Comment by binhnefits** [comment]
hi @bilalaslamseattle I would also like to test this, thanks!

**Comment by guizsantos** [comment]
Hi @bilalaslamseattle , I would love to give it a go as well. Can you please share how we can test it?

**Comment by bilalaslamseattle** [comment]
@ac-garcia @binhnefits @guizsantos I'm going to set up a "drop in" demo for next week. I'd love to get your feedback on the experience and, if you like it, we can enroll you in the preview right there.

Here's are a couple of times next week that you can drop by:
* [EMEA-friendly](https://calendly.com/d/dtn-279-yqn/emea-friendly-demo-of-dbt-in-databricks-workflows)
* [North America-friendly](https://calendly.com/d/dkz-mqb-t75/north-amer-demo-of-dbt-in-databricks-workflows)

Looking forward to seeing you there!

**Comment by bilalaslamseattle** [comment]
I'm going to close this issue as this is not really a bug, and we have a feature under development (dbt task type in Databricks Workflows) which solves for the requirement.
