### ISSUE TITLE
Delta Live Tables

### ISSUE THREAD

**Issue by dwolfeu** [databricks/dbt-databricks#86]
### Describe the feature
Create and orchestrate Delta Live Tables using `dbt-databricks`

### Describe alternatives you've considered
Delta Live Tables can be set up using the Databricks UI, but this misses all the excellent features of dbt.

### Additional context
I do not know whether this idea is feasible, since Delta Live Tables function only in tandem with Databricks pipelines, which goes beyond `CREATE TABLE`.

### Who will this benefit?
Anyone who likes both dbt and Delta Live Tables, in particular teams with existing `dbt-databricks` projects who want to migrate to Delta Live Tables.

### Are you interested in contributing this feature?
Potentially, but I am a complete newbie to this repo.

**Comment by dcaribou** [comment]
dbt + DLT sounds like very powerful combination. I don't know how feasible this is, but I ❤️ the idea.

**Comment by JCZuurmond** [comment]
Is there an update on this enhancement? I am curious!

**Comment by bilalaslamseattle** [comment]
@JCZuurmond please tell me more ... what all would you like to be able to do?

**Comment by Angelo-Baruffi** [comment]
@bilalaslamseattle the ideia is to use all the power of dbt framework, like tests, models, code structure, jinja, dbt utils, etc.. and combine with the power of DLT using streaming data easily.
As @dwolfeu said, its a good integration for teams that already work with dbt

**Comment by bilalaslamseattle** [comment]
@Angelo-Baruffi makes a lot of sense. Thank you!

**Comment by jc-ludia** [comment]
Plus one to what Angelo mentionned so far!

**Comment by followingell** [comment]
Would also love to see this.

**Comment by benc-db** [comment]
We added initial support in 1.6.0, but significant improvements are coming during the 1.7.x timeframe.
