### ISSUE TITLE
Issue with `codegen`, requires changing `dbt/adapters/databricks/relation.py`

### ISSUE THREAD

**Issue by dbeatty10** [databricks/dbt-databricks#863]
### Preamble

See https://github.com/dbt-labs/dbt-codegen/issues/226

I didn't actually assess this issue beyond determining that it looked it belonged in `dbt-databricks` instead of `dbt-codegen`.

So I'm actually not sure if this is a bug or a feature request -- I defer to you @kalebkemp to figure that out along with the rest of the details below.

### Describe the bug
A clear and concise description of what the bug is. What command did you run? What happened?

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**The output of `dbt --version`:**
```
<output goes here>
```

**The operating system you're using:**

**The output of `python --version`:**

**Comment by kalebkemp** [comment]
I can open this with dbt-databricks instead. I think that codegen is calling something in dbt-databricks which is causing the error

**Comment by kalebkemp** [comment]
Oh wow, I'm not smart.. I didn't realize you actually already opened the issue.. I opened another one... 🤦

**Comment by benc-db** [comment]
closing in favor of the new issue
